### ISSUE TITLE
org.traccar.Context not found exception from GWT

### ISSUE THREAD

**Issue by Sargunan** [vitalidze/traccar-web#1023]
Hi ,  

I am getting class not found exception when i try to execute command,  **Please help me to solve this**,

_in my first analysis I found "org.traccar.Context" class is comming from backend, it is not available in Frontend_

   [WARN] Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: Unable to invoke command through reflection
java.lang.ClassNotFoundException: **org.traccar.Context**
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:407)
	at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:383)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.traccar.web.server.model.DataServiceImpl.sendCommand(DataServiceImpl.java:1107)
	at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$e7fcc54f.CGLIB$sendCommand$32(<generated>)
	at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$e7fcc54f$$FastClassByGuice$$4964bcbc.invoke(<generated>)
	at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)

**Comment by vitalidze** [comment]
The command sending is done through "backend" via reflection. You should have that class available to send commands.
