### ISSUE TITLE
MS SQL NEW DATABASE

### ISSUE THREAD

**Issue by adik86** [vitalidze/traccar-web#1058]
Hi, I have a problem to run Traccar in new database in MS SQL 2008, 
When i drop base and create new serwer log generate 

````
INFO|264/0|Service traccar|17-02-05 23:24:06|[INFO] StandardFileSystemManager - Using "C:\Windows\TEMP\vfs_cache" as temporary files store.
INFO|264/0|Service traccar|17-02-05 23:24:08|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO|264/0|Service traccar|17-02-05 23:24:10|[main] INFO com.zaxxer.hikari.pool.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (This operation is not supported.)
INFO|264/0|Service traccar|17-02-05 23:24:11|[main] INFO org.eclipse.jetty.util.log - Logging initialized @8118ms
INFO|264/0|Service traccar|17-02-05 23:24:14|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO|264/0|Service traccar|17-02-05 23:24:19|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@26d820eb{/api,null,AVAILABLE}
INFO|264/0|Service traccar|17-02-05 23:24:33|[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO|264/0|Service traccar|17-02-05 23:24:54|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@be6d228{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-7054362694895259036.dir/webapp/,AVAILABLE}{C:\Program Files\Traccar/traccar-web.war}
INFO|264/0|Service traccar|17-02-05 23:24:54|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@2ae5bd34{HTTP/1.1}{0.0.0.0:8082}
INFO|264/0|Service traccar|17-02-05 23:24:54|[main] INFO org.eclipse.jetty.server.Server - Started @51339ms
INFO|264/0|Service traccar|17-02-05 23:36:27|Feb 05, 2017 11:36:27 PM org.traccar.web.server.model.MethodCallLogger invoke
INFO|264/0|Service traccar|17-02-05 23:36:27|INFO: Login 'admin'
INFO|264/0|Service traccar|17-02-05 23:36:38|[qtp1541525668-112] WARN / - Exception while dispatching incoming RPC call
INFO|264/0|Service traccar|17-02-05 23:36:38|com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.addUser(org.traccar.web.shared.model.User) throws org.traccar.web.shared.model.InvalidMaxDeviceNumberForUserException' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at java.lang.Thread.run(Unknown Source)
INFO|264/0|Service traccar|17-02-05 23:36:38|Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.traccar.web.server.model.DataServiceImpl.addUser(DataServiceImpl.java:256)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.traccar.web.server.model.BackendRefresher.invoke(BackendRefresher.java:40)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at java.lang.reflect.Method.invoke(Unknown Source)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO|264/0|Service traccar|17-02-05 23:36:38|	... 42 more
INFO|264/0|Service traccar|17-02-05 23:36:38|Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:129)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:490)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:195)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:179)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:214)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
INFO|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	... 52 more
FINEST|264/0|Service traccar|17-02-05 23:36:38|Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of UNIQUE KEY constraint 'ui_state_user_name'. Cannot insert duplicate key in object 'dbo.ui_state'. The duplicate key value is (2, archiveGrid).
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:232)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1672)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:460)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:405)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7535)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2438)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:208)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:183)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:348)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
FINEST|264/0|Service traccar|17-02-05 23:36:38|	... 73 more
FINEST|264/0|Service traccar|17-02-05 23:56:07|Feb 05, 2017 11:56:07 PM org.traccar.web.server.model.MethodCallLogger invoke
FINEST|264/0|Service traccar|17-02-05 23:56:07|INFO: Login 'admin'
````

Please tell me what i do wrong?

**Comment by vitalidze** [comment]
It looks weird, I haven't seen such error before. Try disabling unique key constraint from error message. Also it makes sense to search on this issue tracker for other threads related to ms sql.
