### ISSUE TITLE
SEVERE: Unable to send Email message ??

### ISSUE THREAD

**Issue by igor-farias** [vitalidze/traccar-web#1147]
Hi :)
 
I am not a programmer, and not so good with english, but i try, sorry for next wrong words/expressions (using google tradutor to help me).
 
I'm using traccar since april 2017 to track vehicles from org i work. I wasn't the person that have installed traccar system in my org server, but i am responsible for the management.
 
So, i'm having problems with application sending emails.
 
I was thinking was everything ok, but i noticed some events was not being notified by emails. Sometimes i receive emails, sometimes don't, randomly apparently. This occurs always, i never know if i am receiving all emails that the server send to me.

Wrapper log:

> FINEST|53702/0|Service traccar|17-06-19 05:53:54|Jun 19, 2017 5:53:54 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender se
ndEmail
FINEST|53702/0|Service traccar|17-06-19 05:53:54|INFO: Sending Email notification to 'igor.farias@aaa.com.br'...
FINEST|53702/0|Service traccar|17-06-19 05:54:15|Jun 19, 2017 5:54:15 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender se
ndEmail
FINEST|53702/0|Service traccar|17-06-19 05:54:15|INFO: Sending Email notification to 'igor.farias@aaa.com.br'...
FINEST|53702/0|Service traccar|17-06-19 05:54:36|Jun 19, 2017 5:54:36 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender se
ndEmail
FINEST|53702/0|Service traccar|17-06-19 05:54:36|INFO: Sending Email notification to 'igor.farias@aaa.com.br'...
FINEST|53702/0|Service traccar|17-06-19 05:56:44|Jun 19, 2017 5:56:44 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender se
ndEmail
FINEST|53702/0|Service traccar|17-06-19 05:56:44|SEVERE: Unable to send Email message
FINEST|53702/0|Service traccar|17-06-19 05:56:44|com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.aaa.com.br,
25; timeout -1;
FINEST|53702/0|Service traccar|17-06-19 05:56:44|  nested exception is:
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       java.net.ConnectException: Tempo esgotado para conexão (Connection timed out)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at javax.mail.Service.connect(Service.java:295)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at javax.mail.Service.connect(Service.java:176)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at javax.mail.Service.connect(Service.java:125)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:260)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:174)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$8181ee69.CGLIB$doWork$0(<generated>)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$8181ee69$$FastClassByGuice$$3a4208ab.invoke(<generated>)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$8181ee69.doWork(<generated>)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.lang.Thread.run(Thread.java:745)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|Caused by: java.net.ConnectException: Tempo esgotado para conexão (Connection timed out)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.PlainSocketImpl.socketConnect(Native Method)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.Socket.connect(Socket.java:589)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at java.net.Socket.connect(Socket.java:538)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:312)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
FINEST|53702/0|Service traccar|17-06-19 05:56:44|       ... 22 more

At beginning of sample server try send me 3 emails, but in this img of my email box http://imgur.com/a/yKEbV you can see i just received 2 of them.

With this log can you describle the problem i am having? Your help will be usefull!

* @aaa.com.br is a fake email, just for security.

**Comment by vitalidze** [comment]
> com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.aaa.com.br,

This message clearly says that there was an error connecting your SMTP server during sending of some email. However, this sending should happen again until message is expired (by default after 12 hours).

**Comment by igor-farias** [comment]
Yeah, i understand that! But, how can i discover the specific error, and why some email pass and others don't? This makes no sense to me.. :/

**Comment by vitalidze** [comment]
It makes sense to:

* check connection between your server and that SMTP server. Maybe ask your system administrator and/or provider.
* check logs of SMTP server. Ask your server administrator to check whether these messages were received by SMTP server.

**Comment by igor-farias** [comment]
I will check the logs with administrator. Thank you for your assistance!
