### ISSUE TITLE
503 - Service Unavailable

### ISSUE THREAD

**Issue by amir7741** [vitalidze/traccar-web#1160]
Hi,Everybody!
we are using traccar 
your installation guide was very good for H2 database.
but when i was try to change for external mysql DB we had problem :
    1- no data from devices saved in DB.
    2-we cant add users, ---> like some issues from another users.
we was try to do DROP TABLES users and user_devices.
but happen :
   **## 503 - Service Unavailable**
i think traccar cant rebuild this two tables
here is my wrapperLog :

Please help me

//---------------------------------------------------------
WARNING|wrapper|Service traccar|17-08-03 07:12:37|YAJSW: yajsw-beta-12.07
WARNING|wrapper|Service traccar|17-08-03 07:12:37|OS   : Linux/3.4.113-sun8i/arm
WARNING|wrapper|Service traccar|17-08-03 07:12:37|JVM  : Oracle Corporation/1.8.0_131//opt/jdk/jdk1.8.0_131/jre/32
INFO|wrapper|Service traccar|17-08-03 07:12:38|exec:"java" "-classpath" "/opt/traccar/wrapperApp.jar:/opt/traccar/tracker-server.jar:/opt/traccar/lib/log4j-1.2.17.jar:/opt/traccar/lib/joda-time-2.9.6.jar:/opt/traccar/lib/h2-1.4.193.jar:/opt/traccar/lib/mysql-connector-java-5.1.40.jar:/opt/traccar/lib/postgresql-9.4.1212.jre7.jar:/opt/traccar/lib/mssql-jdbc-6.1.0.jre7.jar:/opt/traccar/lib/HikariCP-java7-2.4.9.jar:/opt/traccar/lib/slf4j-api-1.7.21.jar:/opt/traccar/lib/netty-3.10.6.Final.jar:/opt/traccar/lib/async-http-client-1.9.40.jar:/opt/traccar/lib/slf4j-simple-1.7.21.jar:/opt/traccar/lib/javax.json-1.0.4.jar:/opt/traccar/lib/jetty-server-9.2.19.v20160908.jar:/opt/traccar/lib/javax.servlet-api-3.1.0.jar:/opt/traccar/lib/jetty-http-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-io-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-security-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-webapp-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-xml-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-jndi-9.2.19.v20160908.jar:/opt/traccar/lib/jetty-util-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-server-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-common-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-api-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-client-9.2.19.v20160908.jar:/opt/traccar/lib/websocket-servlet-9.2.19.v20160908.jar:/opt/traccar/lib/jersey-container-servlet-2.24.jar:/opt/traccar/lib/jersey-container-servlet-core-2.24.jar:/opt/traccar/lib/javax.inject-2.5.0-b05.jar:/opt/traccar/lib/jersey-common-2.24.jar:/opt/traccar/lib/javax.annotation-api-1.2.jar:/opt/traccar/lib/jersey-guava-2.24.jar:/opt/traccar/lib/hk2-api-2.5.0-b05.jar:/opt/traccar/lib/hk2-utils-2.5.0-b05.jar:/opt/traccar/lib/aopalliance-repackaged-2.5.0-b05.jar:/opt/traccar/lib/hk2-locator-2.5.0-b05.jar:/opt/traccar/lib/javassist-3.20.0-GA.jar:/opt/traccar/lib/osgi-resource-locator-1.0.1.jar:/opt/traccar/lib/jersey-server-2.24.jar:/opt/traccar/lib/jersey-client-2.24.jar:/opt/traccar/lib/jersey-media-jaxb-2.24.jar:/opt/traccar/lib/validation-api-1.1.0.Final.jar:/opt/traccar/lib/javax.ws.rs-api-2.0.1.jar:/opt/traccar/lib/jersey-media-json-jackson-2.24.jar:/opt/traccar/lib/jersey-entity-filtering-2.24.jar:/opt/traccar/lib/jackson-jaxrs-base-2.5.4.jar:/opt/traccar/lib/jackson-core-2.5.4.jar:/opt/traccar/lib/jackson-databind-2.5.4.jar:/opt/traccar/lib/jackson-jaxrs-json-provider-2.5.4.jar:/opt/traccar/lib/jackson-module-jaxb-annotations-2.5.4.jar:/opt/traccar/lib/jackson-annotations-2.5.4.jar:/opt/traccar/lib/liquibase-core-3.5.3.jar:/opt/traccar/lib/snakeyaml-1.17.jar:/opt/traccar/lib/mail-1.4.7.jar:/opt/traccar/lib/activation-1.1.jar:/opt/traccar/lib/jxls-2.3.0.jar:/opt/traccar/lib/commons-jexl-2.1.1.jar:/opt/traccar/lib/commons-logging-1.1.1.jar:/opt/traccar/lib/commons-beanutils-1.9.2.jar:/opt/traccar/lib/jcl-over-slf4j-1.7.12.jar:/opt/traccar/lib/logback-core-1.1.3.jar:/opt/traccar/lib/jxls-poi-1.0.11.jar:/opt/traccar/lib/poi-3.14.jar:/opt/traccar/lib/commons-codec-1.10.jar:/opt/traccar/lib/poi-ooxml-3.14.jar:/opt/traccar/lib/poi-ooxml-schemas-3.14.jar:/opt/traccar/lib/xmlbeans-2.6.0.jar:/opt/traccar/lib/stax-api-1.0.1.jar:/opt/traccar/lib/curvesapi-1.03.jar:/opt/traccar/lib/velocity-1.7.jar:/opt/traccar/lib/commons-collections-3.2.1.jar:/opt/traccar/lib/commons-lang-2.4.jar" "-Dfile.encoding=UTF-8" "-Xrs" "-Dwrapper.service=true" "-Dwrapper.console.visible=false" "-Dwrapper.port=15003" "-Dwrapper.key=2740131982361442466" "-Dwrapper.teeName=2740131982361442466$1501744357141" "-Dwrapper.tmp.path=/opt/traccar/tmp" "-Djna_tmpdir=/opt/traccar/tmp" "-Dwrapper.config=/opt/traccar/conf/wrapper.conf" "-Dwrapper.visible=false" "-Dwrapper.pidfile=/run/wrapper.traccar.pid" "org.rzo.yajsw.app.WrapperJVMMain" 
INFO|wrapper|Service traccar|17-08-03 07:12:38|posix_spawn pid 5320
INFO|wrapper|Service traccar|17-08-03 07:12:38|started process 5320
INFO|wrapper|Service traccar|17-08-03 07:12:38|started process with pid 5320
INFO|5320/0|Service traccar|17-08-03 07:12:43|[INFO] StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
INFO|5320/0|Service traccar|17-08-03 07:12:46|[main] INFO com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Started.
INFO|5320/0|Service traccar|17-08-03 07:12:48|[main] INFO org.eclipse.jetty.util.log - Logging initialized @8409ms
INFO|5320/0|Service traccar|17-08-03 07:12:51|[main] INFO org.eclipse.jetty.server.Server - jetty-9.2.19.v20160908
INFO|5320/0|Service traccar|17-08-03 07:12:59|[main] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@de58ea{/api,null,AVAILABLE}
INFO|5320/0|Service traccar|17-08-03 07:13:03|[main] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO|5320/0|Service traccar|17-08-03 07:13:19|[main] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@1c59ec2{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-112215975676029673.dir/webapp/,STARTING}{/opt/traccar/traccar-web.war}
INFO|5320/0|Service traccar|17-08-03 07:13:19|java.lang.RuntimeException: Unable to perform DB migrations
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:80)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.server.Server.start(Server.java:387)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.web.WebServer.start(WebServer.java:154)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.Main.main(Main.java:40)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at java.lang.reflect.Method.invoke(Method.java:498)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|5320/0|Service traccar|17-08-03 07:13:19|Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.web.server.model.DBMigrations$SetManagerFlag.migrate(DBMigrations.java:172)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.web.server.model.DBMigrations.migrate(DBMigrations.java:74)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:78)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	... 32 more
INFO|5320/0|Service traccar|17-08-03 07:13:19|Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	... 35 more
INFO|5320/0|Service traccar|17-08-03 07:13:19|Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'microlinoTracker.users' doesn't exist
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.Util.getInstance(Util.java:408)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3970)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3906)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2677)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO|5320/0|Service traccar|17-08-03 07:13:19|	... 43 more
INFO|5320/0|Service traccar|17-08-03 07:13:19|[main] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@1533bba{HTTP/1.1}{0.0.0.0:8082}
INFO|5320/0|Service traccar|17-08-03 07:13:19|[main] INFO org.eclipse.jetty.server.Server - Started @39948ms

**Comment by vitalidze** [comment]
Hi

This means you haven't followed [installation instructions](http://traccar.litvak.su/installation.html) carefully. You either haven't dropped original database or haven't disabled database schema upgrades. You need to redo all steps from scratch.
