### ISSUE TITLE
500 - server error

### ISSUE THREAD

**Issue by Preman-Kampung** [vitalidze/traccar-web#1192]
I'm having this 500 - server error message. Already tried restarting using sudo /opt/traccar/bin/startDaemon.sh still the same

FYI: I'm totally don't have any clue about coding or network and any of that stuff. I managed to make work just following instruction from the internet with a LOT of trial and error. And it was my first time using SSH tunnel and linux...

So... any suggestion? Here's the log btw

> FINEST|832/0|Service traccar|18-02-21 22:00:43|
FINEST|832/0|Service traccar|18-02-21 22:00:44|Feb 21, 2018 10:00:44 PM org.jboss.netty.channel.socket.nio.AbstractNioSelector
FINEST|832/0|Service traccar|18-02-21 22:00:44|WARNING: Failed to accept a connection.
FINEST|832/0|Service traccar|18-02-21 22:00:44|java.io.IOException: Too many open files
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
FINEST|832/0|Service traccar|18-02-21 22:00:44|	at java.lang.Thread.run(Thread.java:748)
FINEST|832/0|Service traccar|18-02-21 22:00:44|

> 2018-02-21 21:51:21  INFO: [381D4AC7] id: 273215, time: 2018-02-21 21:51:28, lat: -6.31448, lon: 106.83691, speed: 0.0, course: 0.0
2018-02-21 21:51:27 DEBUG: [D9910DE2: 5055 < 114.4.82.5] HEX: 504f5354202f3f69643d3834343234382674696d657374616d703d31353139323637383934266c61743d2d362e33313432343936266c6f6e3d3130362e383336393230312673706565643d302e302662656172696e673d302e3026616c7469747564653d302e302661636375726163793d32352e3837303030303833393233333426626174743d36312e3020485454502f312e310d0a436f6e74656e742d547970653a206170706c69636174696f6e2f782d7777772d666f726d2d75726c656e636f6465640d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4735333247204275696c642f4d4d42323954290d0a486f73743a206f707469666c616d65732e636f6d3a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:51:27 DEBUG: [D9910DE2: 5055 > 114.4.82.5] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:51:27  WARN: Geocoding failed - maps.googleapis.com - UnknownHostException (... < JsonGeocoder:62 < GeocoderHandler:73 < ... < ExtendedObjectDecoder:74 < ...)
2018-02-21 21:51:27  INFO: [D9910DE2] id: 844248, time: 2018-02-21 21:51:34, lat: -6.31425, lon: 106.83692, speed: 0.0, course: 0.0
2018-02-21 21:52:21 DEBUG: [381D4AC7: 5055 < 120.188.37.198] HEX: 504f5354202f3f69643d3237333231352674696d657374616d703d31353139323637393438266c61743d2d362e33313434393931266c6f6e3d3130362e383336393331362673706565643d302e302662656172696e673d302e3026616c7469747564653d302e302661636375726163793d32382e343338393939313736303235333926626174743d33322e3020485454502f312e310d0a436f6e74656e742d547970653a206170706c69636174696f6e2f782d7777772d666f726d2d75726c656e636f6465640d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4735333247204275696c642f4d4d42323954290d0a486f73743a206f707469666c616d65732e636f6d3a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:52:21 DEBUG: [381D4AC7: 5055 > 120.188.37.198] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:52:21  WARN: Geocoding failed - maps.googleapis.com: System error - UnknownHostException (... < JsonGeocoder:62 < GeocoderHandler:73 < ... < ExtendedObjectDecoder:74 < ...)
2018-02-21 21:52:21  INFO: [381D4AC7] id: 273215, time: 2018-02-21 21:52:28, lat: -6.31450, lon: 106.83693, speed: 0.0, course: 0.0
2018-02-21 21:53:21 DEBUG: [381D4AC7: 5055 < 120.188.37.198] HEX: 504f5354202f3f69643d3237333231352674696d657374616d703d31353139323638303038266c61743d2d362e33313434393833266c6f6e3d3130362e383336393534362673706565643d302e302662656172696e673d302e3026616c7469747564653d302e302661636375726163793d32392e333239303030343733303232343626626174743d33322e3020485454502f312e310d0a436f6e74656e742d547970653a206170706c69636174696f6e2f782d7777772d666f726d2d75726c656e636f6465640d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4735333247204275696c642f4d4d42323954290d0a486f73743a206f707469666c616d65732e636f6d3a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:53:21 DEBUG: [381D4AC7: 5055 > 120.188.37.198] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:53:21  WARN: Geocoding failed - maps.googleapis.com: System error - UnknownHostException (... < JsonGeocoder:62 < GeocoderHandler:73 < ... < ExtendedObjectDecoder:74 < ...)
2018-02-21 21:53:21  INFO: [381D4AC7] id: 273215, time: 2018-02-21 21:53:28, lat: -6.31450, lon: 106.83695, speed: 0.0, course: 0.0
2018-02-21 21:54:22 DEBUG: [381D4AC7: 5055 < 120.188.37.198] HEX: 504f5354202f3f69643d3237333231352674696d657374616d703d31353139323638303639266c61743d2d362e33313434393938266c6f6e3d3130362e383336393038352673706565643d302e302662656172696e673d302e3026616c7469747564653d302e302661636375726163793d32392e37393939393932333730363035343726626174743d33322e3020485454502f312e310d0a436f6e74656e742d547970653a206170706c69636174696f6e2f782d7777772d666f726d2d75726c656e636f6465640d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4735333247204275696c642f4d4d42323954290d0a486f73743a206f707469666c616d65732e636f6d3a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:54:22 DEBUG: [381D4AC7: 5055 > 120.188.37.198] HEX: 485454502f312e3120323030204f4b0d0a436f6e74656e742d4c656e6774683a20300d0a0d0a
2018-02-21 21:54:22  WARN: Geocoding failed - maps.googleapis.com: System error - UnknownHostException (... < JsonGeocoder:62 < GeocoderHandler:73 < ... < ExtendedObjectDecoder:74 < ...)
2018-02-21 21:54:22  INFO: [381D4AC7] id: 273215, time: 2018-02-21 21:54:29, lat: -6.31450, lon: 106.83691, speed: 0.0, course: 0.0

**Comment by vitalidze** [comment]
This issue tracker is about Web UI Modification project for traccar backend. How is your question related with this project?

**Comment by Preman-Kampung** [comment]
I didn't realize this was about web UI issue.I was searching on Google and it take me to this forum, so I assume this the place to get answers. Either way I already post my question on the traccar forum and got what I looking for.

**Comment by Preman-Kampung** [comment]
I didn't realize this was about web UI issue.I was searching on Google and it take me to this forum, so I assume this the place to get answers. Either way I already post my question on the traccar forum and got what I looking for.

**Comment by Preman-Kampung** [comment]
Sorry about that.
