### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by gechdell** [vitalidze/traccar-web#1229]
friends I have a detail when compiling web traccar ui, since I clone the repository and I try to compile it with netbeans and jdk 7 or jdk 8 but it always gives me the same error. 

`testTimeFrameSameTimeZone(org.traccar.web.server.model.NotificationServiceTest)  Time elapsed: 0.001 sec  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.traccar.web.server.model.NotificationServiceTest.testTimeFrameSameTimeZone(NotificationServiceTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)`

I understand that the problem is in NotificationServiceTest.java but I can't find it

**Comment by vitalidze** [comment]
Most probably you have configured your project incorrectly. The `NotificationServiceTest` is under `test` folder along with other source code for JUnit tests.

**Comment by gechdell** [comment]
but where could I look for the error since I clone the repository, and without modifying any line of the code I try to compile and throw that error at me

**Comment by vitalidze** [comment]
Well, you need to figure out how to properly import maven project into your IDE. Also you need to be sure that you are using the `dev` branch.
