### ISSUE TITLE
Remote Procedure Error when loggin only as admin

### ISSUE THREAD

**Issue by joepr** [vitalidze/traccar-web#155]
Hello everyone

I have 2 accounts, admin and manager. When I log as admin I get the following error. However login as manager do not shows the error.
![image](https://cloud.githubusercontent.com/assets/10345032/7338989/c7f20712-ec2c-11e4-9837-841a53ca1205.png)

I installed the latest version to and restarted the whole system however its still showing
My wrapper log shows this:

```
STATUS | wrapper  | 2015/04/26 15:52:14 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/04/26 15:52:14 | Java Service Wrapper Community Edition 64-bit 3.5.25
STATUS | wrapper  | 2015/04/26 15:52:14 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/04/26 15:52:14 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/04/26 15:52:14 | 
STATUS | wrapper  | 2015/04/26 15:52:14 | Launching a JVM...
INFO   | jvm 1    | 2015/04/26 15:52:14 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/04/26 15:52:15 | 2015-04-26 15:52:15.941:INFO:oejs.Server:jetty-8.1.16.v20140903
INFO   | jvm 1    | 2015/04/26 15:52:16 | 2015-04-26 15:52:15.981:INFO:oejw.WebInfConfiguration:Extract jar:file:/opt/traccar/traccar-web.war!/ to /tmp/jetty-0.
0.0.0-8082-traccar-web.war-_-any-/webapp
INFO   | jvm 1    | 2015/04/26 15:52:18 | 2015-04-26 15:52:18.750:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.ser
vlet.JspServlet
INFO   | jvm 1    | 2015/04/26 15:52:23 | 2015-04-26 15:52:22.985:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082
INFO   | jvm 1    | 2015/04/26 15:52:23 | Apr 26, 2015 3:52:22 PM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2015/04/26 15:52:23 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2015/04/26 15:52:23 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Device with id 2
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFoun
d(EntityManagerFactoryBuilderImpl.java:183)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:219)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:275)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:151)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1070)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:989)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:716)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.type.EntityType.resolve(EntityType.java:502)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.type.EntityType.nullSafeGet(EntityType.java:308)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at org.hibernate.persister.collection.AbstractCollectionPersister.readElement(AbstractCollectionPersister.java:8
44)

It also shows this 2 errors

INFO   | jvm 1    | 2015/04/26 15:52:23 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2015/04/26 15:52:23 |   at java.lang.Thread.run(Thread.java:701)
INFO   | jvm 1    | 2015/04/26 15:52:31 | 2015-04-26 15:52:31.227:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/04/26 15:52:31 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.cli
ent.model.DataService.getGeoFences()' threw an unexpected exception: javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Devi
ce with id 2


INFO   | jvm 1    | 2015/04/26 15:52:31 | Caused by: 
INFO   | jvm 1    | 2015/04/26 15:52:31 | javax.persistence.EntityNotFoundException: Unable to find org.traccar.web.shared.model.Device with id 2
INFO   | jvm 1    | 2015/04/26 15:52:31 |   at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFoun
d(EntityManagerFactoryBuilderImpl.java:183)
```

**Comment by joepr** [comment]
Never mind, Seems was a geo-fences related issue. I delete them and add them again. Issue was solve.

**Comment by vitalidze** [comment]
Looks like an issue with devices removal. Device was removed, but it's relation with geo-fence wasn't cleared. Will fix it in next version.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/04/28/bugfix-release.html), updated [latest](myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo](http://traccar.litvak.su/demo.html) versions.
