### ISSUE TITLE
Error in wrapper log file

### ISSUE THREAD

**Issue by studmuffinjj** [vitalidze/traccar-web#157]
Hello,
I am seeing an RPC error in my wrapper log file:

```
com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositions()' threw an unexpected exception: java.lang.SecurityException: Not logged in
```

and then lower down:

```
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
at java.lang.Thread.run(Unknown Source)
Caused by: 
java.lang.SecurityException: Not logged in
```

For the most part, the server seems to work fine except for the following situation - I have 2 models of devices, 1 model works on port 5001, the other on 5013. Often, the devices on 5013 seem to be ignored by the server, no indication that their data is being received. Once the server is restarted, the 5013 devices poll as normal. Restarting the traccar service does not help in this instance. I'm not sure if that issue is related to this error.

I am running the server on a thin client CentOS 6.6 32bit minimal install with Oracle JRE 1.7.0_80. I originally had OpenJDK 1.7 with the same problem. The server has very limited disk space and after about 10 days, the wrapper logs consume about 1GB of disk space with these info messages continuously. I've seen the log file for one day reach as much as 500 Mb.

I get the error with both a vanilla 2.11 and 2.12 traccar install, with and without your modified war file. Default database or MySQL makes no difference.

Are there any other requirements for a CentOS minimal install to stop these errors flooding the logs?

Below is the log snippet with the errors in context.

```
INFO   | jvm 1    | 2015/04/27 23:28:53 | 2015-04-27 23:28:53.015:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/04/27 23:28:53 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositions()' threw an unexpected exception: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/04/27 23:28:53 | Caused by: 
INFO   | jvm 1    | 2015/04/27 23:28:53 | java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.traccar.web.server.model.UserCheck.checkRequireUser(UserCheck.java:69)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:35)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/04/27 23:28:53 |   at java.lang.Thread.run(Unknown Source)
DEBUG  | wrapperp | 2015/04/27 23:28:56 | Send a packet PING : ping 00000989
INFO   | jvm 1    | 2015/04/27 23:28:56 | WrapperManager Debug: Received a packet PING : ping 00000989
INFO   | jvm 1    | 2015/04/27 23:28:56 | WrapperManager Debug: Send a packet PING : ping 00000989
DEBUG  | wrapperp | 2015/04/27 23:28:56 | read a packet PING : ping 00000989
INFO   | jvm 1    | 2015/04/27 23:28:59 | 2015-04-27 23:28:59.016:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/04/27 23:28:59 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getLatestPositions()' threw an unexpected exception: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/04/27 23:28:59 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/04/27 23:28:59 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/04/27 23:28:59 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
```

**Comment by vitalidze** [comment]
This error means that there are some browser instance that survived one (or more) restarts of your service. In such case it will keep polling your server for latest positions, but since session information lives only when application is running, old sessions are not resumed after server restart. So this problem is not related neither with your environment (OS, java version, DBMS type and version, etc.), but with application design.

I suggest you to set up log file rotation on your server (remove old big logs, gzip them, etc.). You can google for some article about using `logrotate` on linux.

**Comment by studmuffinjj** [comment]
Thanks Vitaly. Will try to have logs purged on a regular basis then.
I will see if I can locate any additional information in the logs with regards to port 5013 devices not polling until a server restart. Can't determine if it is a CentOS issue or a traccar issue.
