### ISSUE TITLE
Mail error

### ISSUE THREAD

**Issue by manjoel** [vitalidze/traccar-web#216]
I Installed the latest traccar-web-war since, I can't send an email. I tested I on the demo server there where no problem.

I have installed it on a raspberry 2 where I made thelatest updetes to. 

```
Wrapper: 
INFO   | jvm 1    | 2015/07/15 19:06:46 | Caused by: 
INFO   | jvm 1    | 2015/07/15 19:06:46 | java.lang.IllegalArgumentException: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: XXX.XXXX.XX, 25; timeout -1;|  nested exception is:|?java.net.ConnectException: Die Wartezeit fÃ¼r die Verbindung ist abgelaufen
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.NotificationServiceImpl.checkEmailSettings(NotificationServiceImpl.java:327)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2015/07/15 19:06:46 | Caused by: 
INFO   | jvm 1    | 2015/07/15 19:06:46 | com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.tango.lu, 25; timeout -1;|  nested exception is:|?java.net.ConnectException: Die Wartezeit fÃ¼r die Verbindung ist abgelaufen
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2053)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:386)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:245)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:194)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.NotificationServiceImpl.checkEmailSettings(NotificationServiceImpl.java:324)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2015/07/15 19:06:46 | Caused by: 
INFO   | jvm 1    | 2015/07/15 19:06:46 | java.net.ConnectException: Die Wartezeit fÃ¼r die Verbindung ist abgelaufen
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.PlainSocketImpl.socketConnect(Native Method)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.Socket.connect(Socket.java:589)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.net.Socket.connect(Socket.java:538)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:312)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:236)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:386)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:245)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.mail.Service.connect(Service.java:194)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.NotificationServiceImpl.checkEmailSettings(NotificationServiceImpl.java:324)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:42)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.reflect.Method.invoke(Method.java:483)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/07/15 19:06:46 |   at java.lang.Thread.run(Thread.java:744)
```

Greeds

**Comment by vitalidze** [comment]
Looks like there is a network connection issue between your raspberry pi and smtp server:

```
INFO   | jvm 1    | 2015/07/15 19:06:46 | com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.tango.lu, 25; timeout -1;|
INFO   | jvm 1    | 2015/07/15 19:06:46 | Caused by: 
INFO   | jvm 1    | 2015/07/15 19:06:46 | java.net.ConnectException: Die Wartezeit fÃ¼r die Verbindung ist abgelaufen
```

Please check this out.

**Comment by manjoel** [comment]
I tested arround with various Linux Systems but every where I have the same error message. Is there a package which must be installed, that mail will work.

The bullet Push works

**Comment by vitalidze** [comment]
No package. Maybe it's a firewall that blocks SMTP traffic on your router?

**Comment by manjoel** [comment]
I can send mail from another pc

**Comment by vitalidze** [comment]
Can you do it from traccar server installed on that PC?

**Comment by manjoel** [comment]
yes in a synology nas but i will check it this to be sure if I realy have the same configurations

**Comment by manjoel** [comment]
I verfied it on the nach the email works with the same configurations

**Comment by vitalidze** [comment]
You mean it works in traccar server application or where have you checked it?

**Comment by manjoel** [comment]
I checked it with the sinology status mail, and traccar is running on the nas too, but there the mails are not working

**Comment by vitalidze** [comment]
Can you confirm that sending emails is working on exactly same server with exactly same parameters from any other mail sending application?

**Comment by vitalidze** [comment]
I have lost a bit in all these tests, can you post here the log file from the server (synology I guess) that can send emails from other mailing app, but cannot do that from traccar?

**Comment by vitalidze** [comment]
Any update on this issue?
