### ISSUE TITLE
Installation problem with updated SQL queries

### ISSUE THREAD

**Issue by redge76** [vitalidze/traccar-web#248]
Hi,
I just installed a new traccar server and the installed your UI mod.
I changed the SQL queries as explained in your installation page.
Now I get the following error in the traccar log:
2015-08-27 23:06:10  INFO: [FF5E0224] connected
2015-08-27 23:06:10 DEBUG: [FF5E0224: 5055 < 192.168.1.43] HEX: 474554202f3f69643d6d6f746f2674696d657374616d703d31343430373031393132266c61743d33362....
74696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2015-08-27 23:06:10  WARN: Table "DEVICES" not found; SQL statement:
SELECT \* FROM devices; [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:283 < *:126 < BaseProtocolDecoder.java:43 < ...)

I did not change the "database.createSchema" entry so for me it seems logic that the devices (with s) is impossible to find as I did not change the SQL queries to create the tables. 
Is the schema creation hard coded somewhere in  the code ?

Is there something missing in the installation instructions ?
The UI mod is correctly displayed in the web browser.  Just no data.

Redge

**Comment by vitalidze** [comment]
Looks like you haven't followed the new p.4.1 of instructions which is specific to traccar v3.1

**Comment by redge76** [comment]
hahh... I installed the server 3 days ago... did not refresh the instructions. Commit is from yesterday....
Now it works. Sorry for this.

**Comment by vitalidze** [comment]
No problem. You are welcome.

пятница, 28 августа 2015 г. пользователь redge написал:

> hahh... I installed the server 3 days ago... did not refresh the
> instructions. Commit is from yesterday....
> Now it works. Sorry for this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/248#issuecomment-135560267
> .

## 

Kind regards, Vitaly Litvak

**Comment by korjavin** [comment]
Sorry, but looks like I have some similar problem:
On start I have warning:

```
2015-08-31 08:15:59  WARN: Table "POSITIONS" not found; SQL statement:
SELECT * FROM positions WHERE id IN (SELECT latestPosition_id FROM devices); [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:349 < ConnectionManager.java:41 < ...)

```

but I followed 4.1:
![_763](https://cloud.githubusercontent.com/assets/148765/9574757/46e9c18a-4fe3-11e5-8021-fb702817c5ec.png)

**Comment by vitalidze** [comment]
Your config looks good, do you see following error in `tracker-server.log`?

```
WARN: Need to specify class name in environment or system property, or as an applet parameter, or in an application resource file: java.naming.factory.initial - NoInitialContextException (... < WebServer.java:55 < Context.java:125 < Main.java:26 < ...)
```

**Comment by korjavin** [comment]
The whole file content:

```
2015-08-31 08:27:05  INFO: Operating System name: Linux version: 4.1.0-1-amd64 architecture: amd64
2015-08-31 08:27:05  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.79-b02
2015-08-31 08:27:05  INFO: Memory Limit heap: 1721mb non-heap: 214mb
2015-08-31 08:27:05  INFO: Version: 3.1-SNAPSHOT
2015-08-31 08:27:06  WARN: Table "POSITIONS" not found; SQL statement:
SELECT * FROM positions WHERE id IN (SELECT latestPosition_id FROM devices); [42102-187] - JdbcSQLException (... < QueryBuilder.java:62 < *:132 < DataManager.java:349 < ConnectionManager.java:41 < ...)
2015-08-31 08:27:06  INFO: Starting server...  
```

**Comment by vitalidze** [comment]
Well, it means you actually configured it correctly. Can you check the `wrapper.log` file for error messages? Looks like the `traccar-web` couldn't create necessary tables for some reason.

**Comment by korjavin** [comment]
```
STATUS | wrapper  | 2015/08/31 08:29:35 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/08/31 08:29:35 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/08/31 08:29:35 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/08/31 08:29:35 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/08/31 08:29:35 | 
STATUS | wrapper  | 2015/08/31 08:29:35 | Launching a JVM...
INFO   | jvm 1    | 2015/08/31 08:29:35 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/08/31 08:29:36 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/08/31 08:29:36 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/08/31 08:29:36 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1bqq1hz9b10ba5uu1w65zp1|6ef66f2f, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1bqq1hz9b10ba5uu1w65zp1|6ef66f2f, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/08/31 08:29:36 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @1208ms
INFO   | jvm 1    | 2015/08/31 08:29:37 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.13.v20150730
INFO   | jvm 1    | 2015/08/31 08:29:38 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2015/08/31 08:29:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.w.WebAppContext@576a7290{/,file:/tmp/jetty-0.0.0.0-8082-traccar-web.war-_-any-619806434406008986.dir/webapp/,AVAILABLE}{/opt/traccar/traccar-web.war}
INFO   | jvm 1    | 2015/08/31 08:29:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@1be2bc0{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2015/08/31 08:29:41 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @6067ms
INFO   | jvm 1    | 2015/08/31 08:29:49 | [qtp2085636231-50] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/08/31 08:29:49 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.authenticated()' threw an unexpected exception: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/08/31 08:29:49 | Caused by: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.traccar.web.server.model.UserCheck.checkRequireUser(UserCheck.java:70)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:36)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/08/31 08:29:49 |   ... 41 more
INFO   | jvm 1    | 2015/08/31 08:29:53 | Aug 31, 2015 8:29:53 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2015/08/31 08:29:53 | INFO: Login 'admin'
```

**Comment by vitalidze** [comment]
It looks good too. I am out of ideas. Have you restarted service? Maybe you can check which tables do you have in your database?

**Comment by korjavin** [comment]
Yes, I tryed to restart,the same.
I am ready to do anything what could help, but I am far away from java and h2 databases.

There are my databases:
https://yadi.sk/d/REBBPTWvimPAM
https://yadi.sk/d/ypIxrudGimPAR

**Comment by vitalidze** [comment]
This database has necessary tables:

```
$ java -cp lib/h2-1.4.187.jar org.h2.tools.Shell 

Welcome to H2 Shell 1.4.187 (2015-04-10)
Exit with Ctrl+C
[Enter]   jdbc:h2:~/Documents/traccar-web/database
URL       jdbc:h2:~/Downloads/database
[Enter]   org.h2.Driver
Driver    
[Enter]   sa
User      sa
[Enter]   Hide
Password  
Password  
Connected
Commands are case insensitive; SQL statements end with ';'
help or ?      Display this help
list           Toggle result list / stack trace mode
maxwidth       Set maximum column width (default is 100)
autocommit     Enable or disable autocommit
history        Show the last 20 statements
quit or exit   Close the connection and exit

sql> show tables;
TABLE_NAME             | TABLE_SCHEMA
APPLICATION_SETTINGS   | PUBLIC
DEVICES                | PUBLIC
DEVICES_GEOFENCES      | PUBLIC
DEVICE_ICONS           | PUBLIC
EVENTS                 | PUBLIC
GEOFENCES              | PUBLIC
MAINTENANCES           | PUBLIC
NOTIFICATION_SETTINGS  | PUBLIC
NOTIFICATION_TEMPLATES | PUBLIC
PICTURES               | PUBLIC
POSITIONS              | PUBLIC
SENSORS                | PUBLIC
UI_STATE               | PUBLIC
USERS                  | PUBLIC
USERS_DEVICES          | PUBLIC
USERS_GEOFENCES        | PUBLIC
USERS_NOTIFICATIONS    | PUBLIC
USER_SETTINGS          | PUBLIC
(18 rows, 54 ms)
sql> 
```

Looks like it is from `~/Documents` folder because it don't have tables from original traccar database (like `position`, etc.). Where did you got this database?

**Comment by korjavin** [comment]
/opt/traccar# scp data/database.\* 

from /opt/traccar/data/ folder

**Comment by vitalidze** [comment]
Well, I am out of ideas. I can tell that now web UI works fine with your database, but backend which is responsible for collecting data from devices works with a different database.

I suggest you to install MySQL and configure traccar to use it. It will save you much time since it is more stable, fast, scalable than the default H2 database.

If it does not work for you I suggest you to start from scratch and do it step-by-step:

1) Install original version of traccar
2) Make sure it works with your device with original web UI (like test from mobile phone app)
3) Install my web UI mod following official instructions http://traccar.litvak.su/installation.html

If even this does not work then the only left option I can see is that you give me access to your server and I will try installing it for you.

**Comment by korjavin** [comment]
I just made docker image with my installation
https://hub.docker.com/r/korjavin/traccar-web/
if you use it, you can see exactly same state what I have.
There is https://github.com/korjavin/docker-traccar/tree/customweb Dockerfile for it, if you like to build.

Also I can share ssh with my installation, or anything else.

I like this webui, so ready to any steps which may help.

**Comment by korjavin** [comment]
my problem disappeared when device sent data

**Comment by webmst** [comment]
I had had the same idea (new data may force table creation) but I'm sorry it cannot go that way.

My device (traccar client 3.5 on android using the new 'osmand' protocol on port 5055) is still displaying errors in sending data ("send failed") to the server (while traccar.log is confirming a stream of data just being received) before appending to the 'devices' table, as you can see:

2015-08-31 20:33:14 DEBUG: [822796AD: 5055 < 192.168.0.235] HEX: 474554202f3f696
43d3335353230313230393233343533382674696d657374616d703d31343430383730313936266c61743d34342e3931323433383333333333333333266c6f6e3d382e3631343534333333333333333333342673706565643d302e302662656172696e673d3235302e363130303030363130333531353626616c7469747564653d3135382e3526626174743d38352e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f312e362e3020284c696e75783b20553b20416e64726f696420342e312e313b2047542d6939333030204275696c642f494d4d373644290d0a486f73743a20636470612e6e6f69702e6d653a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2015-08-31 20:33:14  WARN: Table 'traccar.devices' doesn't exist - MySQLSyntaxEr
rorException (... < QueryBuilder.java:289 < DataManager.java:283 < *:126 < BaseP
rotocolDecoder.java:43 < ...)

I don't know if this is the case (i.e. if there is a bidirectional protocol with return code), but it seems that the client is now 'aware' that its data haven't been stored (that was not happening before if the given device hadn't been registered yet).

**Comment by vitalidze** [comment]
From my investigation I find that this message is normal for the first start because so-called `ConnectionManager` initialisation happens BEFORE initialisation of web part, which creates the necessary table. So for the first time you will get this warning. Then it is required to restart the server. After restarting it should work just fine. I will update instructions accordingly to this double `restart` issue.
