### ISSUE TITLE
Problems with restart

### ISSUE THREAD

**Issue by novak82** [vitalidze/traccar-web#282]
I have installed traccar according to instructions http://traccar.litvak.su/installation.html , and it worked well, but it reports problem when I want to restart . I have noticed that when I delete files from /opt/traccar/data it starts, but it do not restarts.

```
STATUS | wrapper  | 2015/10/13 15:12:12 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/10/13 15:12:12 | Java Service Wrapper Community Edition 64-bit 3.5.26
STATUS | wrapper  | 2015/10/13 15:12:12 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/10/13 15:12:12 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/10/13 15:12:12 |
STATUS | wrapper  | 2015/10/13 15:12:12 | Launching a JVM...
INFO   | jvm 1    | 2015/10/13 15:12:12 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/10/13 15:12:13 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/10/13 15:12:13 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/10/13 15:12:13 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1br9spn9cr076gn1jr1hyu|36bf7795, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1br9spn9cr076gn1jr1hyu|36bf7795, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp:
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error: java.lang.NullPointerException
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder$6.process(QueryBuilder.java:371)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder$6.process(QueryBuilder.java:367)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.database.QueryBuilder.executeQuery(QueryBuilder.java:393)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.database.DataManager.getLatestPositions(DataManager.java:349)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.database.ConnectionManager.<init>(ConnectionManager.java:41)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.Context.init(Context.java:102)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.traccar.Main.main(Main.java:26)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2015/10/13 15:12:13 | WrapperSimpleApp Error:       at java.lang.Thread.run(Thread.java:745)
STATUS | wrapper  | 2015/10/13 15:12:15 | <-- Wrapper Stopped
```

**Comment by vitalidze** [comment]
Which version of traccar are you using?

Have you updated the following query in configuration file?:

```
<entry key='database.insertPosition'>
    INSERT INTO positions (device_id, protocol, serverTime, time, valid, latitude, longitude, altitude, speed, course, address, other)
    VALUES (:deviceId, :protocol, CURRENT_TIMESTAMP(), :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :address, :other);
</entry>
```

The thing is that new version has the `serverTime` field, which will be NULL by default after the upgrade.

**Comment by novak82** [comment]
I missed this changes.
But, it was strange that it works when there are no database files.

Thanks,

**Comment by vitalidze** [comment]
It works because there are no data. In particular it fails when it tries to read latest positions and in one of the column there is 'NULL'. Probably it can be fixed by updating the `database.selectLatestPositions` query to include specific columns (i.e. skip `serverTime` column with NULLs).

**Comment by ghost** [comment]
Hello,
I've exactly the same problem. So I made the change I've missed too, as
<entry key='database.insertPosition'>
and now again..  impossible to start the service !

**Comment by vitalidze** [comment]
If you have existing database you will need to update it as well. I suggest to run the following query:

```
UPDATE positions SET serverTime=time WHERE serverTime IS NULL
```

**Comment by ghost** [comment]
I get an
Unknown command

**Comment by vitalidze** [comment]
You need to open your database with some tool that allows you to run SQL queries. For H2 this can be a [Shell tool](http://www.h2database.com/html/tutorial.html#shell_tool) and for MySQL there is a command line client called `mysql`.
