### ISSUE TITLE
Log in and wrapper log 

### ISSUE THREAD

**Issue by novak82** [vitalidze/traccar-web#289]
I noticed that the every access to log in screen was recorded in the wrapper log as an error connected with authentication, even if there was no other activities like entering username or password. 
Is that expacted?

```
INFO   | jvm 1    | 2015/10/21 10:31:50 | [qtp530043696-35] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/10/21 10:31:50 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.authenticated()' threw an unexpected exception: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/10/21 10:31:50 | Caused by: java.lang.SecurityException: Not logged in
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.traccar.web.server.model.UserCheck.checkRequireUser(UserCheck.java:70)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:36)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/10/21 10:31:50 |   ... 41 more
INFO   | jvm 1    | 2015/10/21 10:31:57 | Oct 21, 2015 10:31:56 AM org.traccar.web.server.model.MethodCallLogger invoke
```

**Comment by vitalidze** [comment]
Short answer: yes, it is expected behaviour in current implementation.

Long answer: it comes from original implementation. Once web application starts up it invokes a RPC method, which breaks if there are no authentication info. In case it is broken the login screen is shown, in other case it proceeds to load the application. The error is logged on the higher level - in servlet container. This means that in current implementation it is not easy to both throw an error and skip logging.

I agree that this is confusing and I think I will change it in the next release so the error will not be logged. The authentication check call will just return either true or false. This should be enough for authentication check purpose.

**Comment by vitalidze** [comment]
Implemented, [written news](http://traccar.litvak.su/2015/11/17/Reports,-neptune-theme,-notifications-on-overspeed.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
