### ISSUE TITLE
Scheduled task error every minute

### ISSUE THREAD

**Issue by alvarengasv** [vitalidze/traccar-web#338]
I'm getting this error every minute in the service wrapper log. Restarting the service doesn't fix it. This is preventing the website from sending most notifications. It looks like the only notification that works is "went offline".

```
INFO   | jvm 1    | 2015/11/18 08:21:02 | Nov 18, 2015 8:21:02 AM org.traccar.web.server.model.ScheduledTask run
INFO   | jvm 1    | 2015/11/18 08:21:02 | SEVERE: Error during scheduled task execution
INFO   | jvm 1    | 2015/11/18 08:21:02 | java.lang.IllegalArgumentException: id to load is required for loading
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:109)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.event.spi.LoadEvent.<init>(LoadEvent.java:79)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.internal.SessionImpl$IdentifierLoadAccessImpl.load(SessionImpl.java:2548)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.internal.SessionImpl.get(SessionImpl.java:955)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1110)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:1068)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.traccar.web.server.model.EventServiceImpl$PositionScanner.doWork(EventServiceImpl.java:162)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2015/11/18 08:21:02 |   at java.lang.Thread.run(Unknown Source)
```

**Comment by vitalidze** [comment]
Yeah, I am aware of that. Already fixed it today's morning, but haven't pushed changes to github yet. The 'offline' notifications work because they use different approach for event posting.

**Comment by vitalidze** [comment]
Fixed, [written news](http://traccar.litvak.su/2015/11/19/Bugfix,-and-mobile-geolocation.html), updated [latest](http://traccar.litvak.su/installation.html) and [demo](http://traccar.litvak.su/demo.html) versions.
