### ISSUE TITLE
Remote procedure call error

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#391]
Часто при авторизации выдает ошибку: "Remote procedure call error". Геозоны после такой ошибки не отображаются, иногда бывает, что и объекты тоже не отображаются. Лечится либо после перезапуска mysql и traccar серверов, либо если несколько раз нажать кнопку F5 в браузере. В чем может быть проблема?  

Вот лог: 

```
INFO   | jvm 1    | 2015/12/09 12:45:31 | Dec 09, 2015 12:45:30 PM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2015/12/09 12:45:31 | INFO: Login 'admin'
INFO   | jvm 1    | 2015/12/09 12:45:31 | [qtp24087440-34] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/12/09 12:45:31 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.lang.String org.traccar.web.client.model.UIStateService.getValue(java.lang.String)' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:64)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 41 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:76)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1435)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:61)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 47 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
INFO   | jvm 1    | 2015/12/09 12:45:31 | 
INFO   | jvm 1    | 2015/12/09 12:45:31 | The last packet successfully received from the server was 83,804 milliseconds ago.  The last packet sent successfully to the server was 1 milliseconds ago.
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3434)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3334)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3774)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2541)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4882)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mchange.v2.c3p0.impl.NewProxyConnection.setAutoCommit(NewProxyConnection.java:1059)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:72)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 50 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2926)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3344)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 58 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | [qtp24087440-30] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/12/09 12:45:31 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract java.util.List org.traccar.web.client.model.DataService.getGeoFences()' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: javax.persistence.PersistenceException: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:64)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:62)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 41 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: org.hibernate.TransactionException: JDBC begin transaction failed: 
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:76)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.begin(AbstractTransactionImpl.java:162)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.internal.SessionImpl.beginTransaction(SessionImpl.java:1435)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.jpa.internal.TransactionImpl.begin(TransactionImpl.java:61)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 47 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
INFO   | jvm 1    | 2015/12/09 12:45:31 | 
INFO   | jvm 1    | 2015/12/09 12:45:31 | The last packet successfully received from the server was 348,594 milliseconds ago.  The last packet sent successfully to the server was 0 milliseconds ago.
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1038)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3434)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3334)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3774)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2541)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:4882)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mchange.v2.c3p0.impl.NewProxyConnection.setAutoCommit(NewProxyConnection.java:1059)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.doBegin(JdbcTransaction.java:72)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 50 more
INFO   | jvm 1    | 2015/12/09 12:45:31 | Caused by: java.io.EOFException: Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:2926)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   at com.mysql.jdbc.MysqlIO.reuseAndReadPacket(MysqlIO.java:3344)
INFO   | jvm 1    | 2015/12/09 12:45:31 |   ... 58 more
```

**Comment by vitalidze** [comment]
Похоже на проблему из #176/#355. Основная причина - нестандартный настройки таймаута MySQL. Почитайте комментарий: https://github.com/vitalidze/traccar-web/issues/176#issuecomment-111690177

**Comment by ghost** [comment]
Спасибо, помогло увеличение в MySQL wait_timeout на 600.
