### ISSUE TITLE
Wierd error on adding devices

### ISSUE THREAD

**Issue by abhishekricky** [vitalidze/traccar-web#442]
Hi,

when I am adding devices its not showing real time and there is this error in logs 

```
INFO   | jvm 1    | 2015/12/31 19:59:53 | Dec 31, 2015 7:59:53 PM org.traccar.web.server.model.BackendRefresher refreshWithAPI
INFO   | jvm 1    | 2015/12/31 19:59:53 | WARNING: Unable to refresh permissions via API
INFO   | jvm 1    | 2015/12/31 19:59:53 | java.net.ConnectException: Connection timed out
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.PlainSocketImpl.socketConnect(Native Method)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.Socket.connect(Socket.java:579)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.Socket.connect(Socket.java:528)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.http.HttpClient.New(HttpClient.java:308)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.http.HttpClient.New(HttpClient.java:326)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:998)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:934)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:852)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1302)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.BackendRefresher.refreshWithAPI(BackendRefresher.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.BackendRefresher.invoke(BackendRefresher.java:42)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$11ae56e1.addDevice(<generated>)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2015/12/31 19:59:53 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2015/12/31 19:59:53 | 
```

**Comment by abhishekricky** [comment]
@vitalidze  this I am seeing also on local, but on remote server with traccar code 3.2. Any device is being added but not reflecting

**Comment by vitalidze** [comment]
This is not critical error, but a warning. It means the web UI was not able to refresh permissions on the backend, which required to send commands properly. Just ignore it. Especially if you run from the IDE (Eclipse, Idea, NetBeans).

**Comment by abhishekricky** [comment]
Hi,

Problem is when I m adding a device or deleting , its reflecting on the web after 30 minutes

But at same time I am seeing its visible in the database 

Ya code is deployed on server I used traccar v3.2 as base

**Comment by vitalidze** [comment]
I haven't heard about such issue. Just tried on my demo server and it works just fine. Are you using latest version from the web site?

**Comment by abhishekricky** [comment]
Yes I am using latest version

**Comment by abhishekricky** [comment]
Hi,

Well I am seeing on one server on digitalocean its working , but this slow refresh of data automattically after adding is slow on azure . What can be the issue that I would have to look into in Azure

**Comment by vitalidze** [comment]
I have no idea what's wrong with azure. You should check it with your web browser tools. Maybe it has something to do with the networking bandwidth, firewall, etc.

**Comment by abhishekricky** [comment]
does it have anything to do with java ? installation becoz on ubuntu I had used openjre and openjdk

**Comment by vitalidze** [comment]
I don't think so. It should run just fine on OpenJDK.

**Comment by abhishekricky** [comment]
Backend refresh happens via gwt functions right? must be jvm interprocess interaction is an issue

**Comment by vitalidze** [comment]
Code written with GWT is compiled into javascript. There are no JVM interaction there. The backend running java exposes an API, which is then invoked with javascript. You can see this call with method parameters, name and so on right in your web browser.
