### ISSUE TITLE
Notification email error

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#461]
Hello,

Emails alerts are not send.

My  'test email notification' is OK
User's email account has the GOOD email address
In user account  ALL notifications are checked

My system log show me that......

```
INFO   | jvm 1    | 2016/01/11 15:12:47 | Jan 11, 2016 3:12:46 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/01/11 15:12:47 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2016/01/11 15:12:47 | javax.mail.SendFailedException: Invalid Addresses;
INFO   | jvm 1    | 2016/01/11 15:12:47 |   nested exception is:
INFO   | jvm 1    | 2016/01/11 15:12:47 |   com.sun.mail.smtp.SMTPAddressFailedException: 550 Destinataire inconnu - Unknown recipient (adresse@hotmail.fr)
INFO   | jvm 1    | 2016/01/11 15:12:47 | 
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1949)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1195)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:250)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:162)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$49661b2c.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$49661b2c$$FastClassByGuice$$3eb4449d.invoke(<generated>)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$49661b2c.doWork(<generated>)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/01/11 15:12:47 | Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 Destinataire inconnu - Unknown recipient (adresse@hotmail.fr)
INFO   | jvm 1    | 2016/01/11 15:12:47 | 
INFO   | jvm 1    | 2016/01/11 15:12:47 |   at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1802)
INFO   | jvm 1    | 2016/01/11 15:12:47 |   ... 19 more
INFO   | jvm 1    | 2016/01/11 15:12:47 | 
INFO   | jvm 1    | 2016/01/11 15:12:47 | Jan 11, 2016 3:12:47 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/01/11 15:12:47 | INFO: Sending Email notification to 'adresse@hotmail.fr'...
INFO   | jvm 1    | 2016/01/11 15:12:50 | Jan 11, 2016 3:12:50 PM org.traccar.web.server.model.MethodCallLogger invoke
```

I tried also 
settings/notifications/message templates/ choose a message and click on test
I never receive this test email !

In this log, I changed the real address by    adresse@hotmail.fr    but I checked many times in user, and the true email address is OK, I also sent tests emails to this one by other's senders addresses and all tests emails goes inside the inbox.
I don't have a user email address problem, it is correct.

So, what' else please ????

**Comment by vitalidze** [comment]
> I tried also 
> settings/notifications/message templates/ choose a message and click on test
> I never receive this test email !

'Test' does not send any email. In email templates it just generates the preview. In Notification Settings it just tries to start a session with your SMTP server to check whether address and credentials are correct.

> In this log, I changed the real address by adresse@hotmail.fr but I checked many times in user, and the true email address is OK, I also sent tests emails to this one by other's senders addresses and all tests emails goes inside the inbox.
> I don't have a user email address problem, it is correct.
> 
> So, what' else please ????

This issue is definitely with your SMTP server. Are you sure you can send email to that 'problematic' address with absolutely same SMTP server settings from a different email client (like from Outlook or Thunderbird or linux `mail` application)? Please read [this about the 550 SMTP code](http://www.serversmtp.com/en/error-550), which says that this can be rejected with a spam filter.

**Comment by ghost** [comment]
Thanks for you help,
After stopping restarting the serveur... user receive it's notifications...   BUT, I think there is a little bug, if I modify the email address, This new "to" address is not use immediately by traccar. I need to restart traccar !!!!

**Comment by vitalidze** [comment]
This sounds like a bug in notification sending system. I will check this out later.

**Comment by waca98** [comment]
Thanks, and now, I receive notifications..... but.....
The subject is  OK, while the body is 

Unknown message
