### ISSUE TITLE
Pushbullet

### ISSUE THREAD

**Issue by ghost** [vitalidze/traccar-web#495]
Hello,

I don't receive "pushbullet" notification.
My token seem OK, because test say  OK

```
INFO   | jvm 1    | 2016/02/01 17:04:21 | INFO: Sending Pushbullet notification to 'zou@email.com'...
INFO   | jvm 1    | 2016/02/01 17:04:22 | Feb 01, 2016 5:04:22 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendPushbullet
INFO   | jvm 1    | 2016/02/01 17:04:22 | SEVERE: I/O Error
INFO   | jvm 1    | 2016/02/01 17:04:22 | java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.pushbullet.com/v2/pushes
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendPushbullet(NotificationServiceImpl.java:291)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:163)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$cfda362c.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$cfda362c$$FastClassByGuice$$ee610eca.invoke(<generated>)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$cfda362c.doWork(<generated>)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/02/01 17:04:22 |   at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/02/01 17:04:22 | 
INFO   | jvm 1    | 2016/02/01 17:04:22 | Feb 01, 2016 5:04:22 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail

```

**Comment by vitalidze** [comment]
Code 429 means "Too many requests". Looks like you have reached some limit on the number of requests on pushbullet.

**Comment by waca98** [comment]
I've more info about that.... after a 
service traccar restart
I receive all pushbullet.

**Comment by ghost** [comment]
I've more info about that.... after a 
service traccar restart
I receive all pushbullet.
