### ISSUE TITLE
Email Notification Stop Working

### ISSUE THREAD

**Issue by joepr** [vitalidze/traccar-web#643]
Hello Group

I have been using Gmail as my SMTP for more than 1 month and it was working just fine until yesterday. For some strange reason I'm not receiving my notifications. Before this happened the only changes I made was:
- Create a new account . Example Bob
- Transfer a currently working GPS tracker from Liza to Bob. 

The new Bob account shows up the tracker and Geofences seems to be working. Under Reports I can see when the tracker has gone In & Out. However no notifications so far. 

I do also notice I stop receiving Liza notifications as well. Here is my server wrapper log . For security purpose in this post the email account was changed to user@gmail.com . 

I verify that current emails account receive and send messages directly from Gmail platform. I do also verify under the admin account - Notification Settings and when trying to test it shows up this error

![image](https://cloud.githubusercontent.com/assets/10345032/14783951/0bbecfa8-0ac1-11e6-8474-d50291e2b4ec.png)

`$EnhancerByGuice$$f8957a67$$FastClassByGuice$$58dbf60f.invoke(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67.doWork(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/25 07:11:50 |   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2016/04/25 07:11:50 | 
INFO   | jvm 1    | 2016/04/25 07:11:50 | Apr 25, 2016 7:11:50 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/04/25 07:11:50 | INFO: Sending Email notification to 'user@gmail.com'...
INFO   | jvm 1    | 2016/04/25 07:11:51 | Apr 25, 2016 7:11:51 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/04/25 07:11:51 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2016/04/25 07:11:51 | javax.mail.AuthenticationFailedException: 454 4.7.0 Too many login attempts, please try again later. 21sm5972205ual.21 - gsmtp
INFO   | jvm 1    | 2016/04/25 07:11:51 | 
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:892)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:814)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:728)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at javax.mail.Service.connect(Service.java:386)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at javax.mail.Service.connect(Service.java:245)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at javax.mail.Service.connect(Service.java:194)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:249)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:162)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67.CGLIB$doWork$1(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67$$FastClassByGuice$$58dbf60f.invoke(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67.doWork(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/25 07:11:51 |   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2016/04/25 07:11:51 | 
INFO   | jvm 1    | 2016/04/25 07:11:51 | Apr 25, 2016 7:11:51 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/04/25 07:11:51 | INFO: Sending Email notification to 'user@gmail.com'...
INFO   | jvm 1    | 2016/04/25 07:11:52 | Apr 25, 2016 7:11:51 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/04/25 07:11:52 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2016/04/25 07:11:52 | javax.mail.AuthenticationFailedException: 454 4.7.0 Too many login attempts, please try again later. m89sm1290439uam.15 - gsmtp
INFO   | jvm 1    | 2016/04/25 07:11:52 | 
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:892)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.sun.mail.smtp.SMTPTransport.authenticate(SMTPTransport.java:814)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:728)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at javax.mail.Service.connect(Service.java:386)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at javax.mail.Service.connect(Service.java:245)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at javax.mail.Service.connect(Service.java:194)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:249)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:162)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67.CGLIB$doWork$1(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67$$FastClassByGuice$$58dbf60f.invoke(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$f8957a67.doWork(<generated>)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/04/25 07:11:52 |   at java.lang.Thread.run(Thread.java:744)
INFO   | jvm 1    | 2016/04/25 07:11:52 | 
INFO   | jvm 1    | 2016/04/25 07:11:52 | Apr 25, 2016 7:11:51 AM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/04/25 07:11:52 | INFO: Sending Email notification to 'user@gmail.com'...`

**Comment by gsiotas** [comment]
According to Gmail:

> The Gmail mail server send limit is approximately 100-150 emails per day when connected to the server from a remote email client. You can send 500 emails each day through the Gmail SMTP server when logged into their web interface

So if server sends more than 100-150 emails per day then you encounter the problem you mention

**Comment by wolfbgn** [comment]
You can install on the same machine where Traccar is or on other machine on the same LAN some mail server like iRedmail. Sending mail never go outside your network and you have no problem with spam.
If you have several devices or hundreds - it is the same. You always get the notifications
