### ISSUE TITLE
add group Remote procedure call error

### ISSUE THREAD

**Issue by bhrached** [vitalidze/traccar-web#655]
Hello,
I installed web-traccar everything works perfectly but when I add a group I see the message "Remote procedure call error"
I use traccar 3.5
You will find the error message in the browser console:
traccar-0.js:6451 POST http://X.X.X.X:8082/traccar/groupService 500 (Server Error)

thank you in advance

**Comment by vitalidze** [comment]
This sounds like a bug. Please show contents of latest `wrapper.log` file right after you reproduce the issue.

**Comment by bhrached** [comment]
```
INFO   | jvm 1    | 2016/05/02 23:03:29 | [qtp1329832935-38] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/05/02 23:03:29 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.Group org.traccar.web.client.model.GroupService.addGroup(org.traccar.web.shared.model.Group,org.traccar.web.shared.model.Group)' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/05/02 23:03:29 | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1683)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1187)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.traccar.web.server.model.GroupServiceImpl.addGroup(GroupServiceImpl.java:72)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at java.lang.reflect.Method.invoke(Method.java:606)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       ... 42 more
INFO   | jvm 1    | 2016/05/02 23:03:29 | Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:72)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.id.IdentityGenerator$GetGeneratedKeysDelegate.executeAndExtract(IdentityGenerator.java:96)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:58)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3032)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3558)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:98)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:490)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:195)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:179)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:214)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:324)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:288)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:194)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:125)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.event.internal.core.JpaPersistEventListener.saveWithGeneratedId(JpaPersistEventListener.java:84)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:206)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:149)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:75)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:811)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:784)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:789)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.jpa.spi.AbstractEntityManagerImpl.persist(AbstractEntityManagerImpl.java:1181)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       ... 51 more
INFO   | jvm 1    | 2016/05/02 23:03:29 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'name' cannot be null
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:932)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/05/02 23:03:29 |       ... 72 more
```

**Comment by vitalidze** [comment]
I think you have wrong structure for table named `groups` inside your database. It looks like it comes from the original traccar database, which has the `name` column `NOT NULL`. I think you have set up the Traccar Web UI Mod - skipped the step with disabling backend database schema updates and dropping all tables from the database BEFORE starting the service.

The easiest way to solve it is to drop 'not nullable' flag from the `name` column of the `groups` table. Or you can just drop the whole table `groups` and restart the service so it will be created back. You need to make sure that you have disabled backend schema updates by removing/commenting of out the following block in `traccar.xml` configuration file:

``` xml
<entry key='database.changelog'>./database/changelog-master.xml</entry>
```

**Comment by bhrached** [comment]
I solved the problem by running the MySQL command

``` sql
ALTER TABLE  `groups` CHANGE  `name`  `name` VARCHAR( 128 ) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL ;
```

**Comment by vitalidze** [comment]
This looks good, but I think you should better use `utf8` encoding for the column to avoid issues with language-specific characters.

**Comment by bhrached** [comment]
by cons when I add a user I get "the Username is already taken" on the message and log file I apprecoi this message INFO   | jvm 1    | 2016/05/03 16:25:44 | Caused by: java.sql.SQLException: Field 'name' doesn't have a default value

**Comment by vitalidze** [comment]
This is caused by exactly same reason as I described in my first answer. You are trying to apply the web UI Mod over original tables of traccar. The instructions say that you need to drop all original tables and then let the web UI Mod create appropriate structure by itself. Otherwise you will continue facing issues like this.

**Comment by bhrached** [comment]
I made the following statements?
0- I made a stop traccar
1- I made a drop databae
2-I create the database again.
3- I commented <entry key = 'database.changelog'> ./ database / changelog-master.xml </ entry>
4- I made a start traccar
Thank you for confirmmer

**Comment by vitalidze** [comment]
Yes, you should have the correct database structure after following these steps. So it should be fine then.

**Comment by bhrached** [comment]
The position of the tracker android client are not recording dan comics and I have these errors in the log
2016-05-04 12:47:24  WARN: Table 'Mytrack.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457 < PermissionsManager:74 < ...)
2016-05-04 12:47:25  WARN: Table 'Mytrack.positions' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < DataManager:452 < ConnectionManager:55 < ...)
2016-05-04 12:47:25  INFO: Starting server...
2016-05-04 12:51:58  WARN: Table 'Mytrack.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457 < PermissionsManager:74 < ...)

**Comment by vitalidze** [comment]
> 2016-05-04 12:47:24 WARN: Table 'Mytrack.server' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < *:275 < DataManager:457 < PermissionsManager:74 < ...)

This can be safely ignored.

> 2016-05-04 12:47:25 WARN: Table 'Mytrack.positions' doesn't exist - MySQLSyntaxErrorException (... < QueryBuilder:376 < DataManager:452 < ConnectionManager:55 < ...)

This means you have incorrect database structure. BTW, why your database is named `Mytrack` starting from a capital letter? Are you sure it is a correct name?

**Comment by bhrached** [comment]
falsehood has vanished when I restart again once the service and positions without saving in the DB. Thank You
