### ISSUE TITLE
issues with sql server

### ISSUE THREAD

**Issue by cabreu1981** [vitalidze/traccar-web#669]
i'm having a big issue when using the mod with SQL Server, 
the first is the event table is not created, i had to create it manually,
the table server is not created, i had to create it manually,
until that there's not a big issue but looks like all constrains a foreign keys are wrong,
i cannot add a device, or group or anything, just modify the the fields that not required constrains
on other tables,
another issue is that for save a vehicle, no sql, using h2 you had to click on all 
tabs to be able to save it, can you verify that, 
Regards.

**Comment by vitalidze** [comment]
Have you deleted all tables before the first startup with the web UI Mod
configured? There should not be a "server" table.

Also are you sure you are using latest version of the project? I remember
an issue with the device saving, but I fixed it just before release.

понедельник, 9 мая 2016 г. пользователь Carlos Fabian Abreu Valerio написал:

> i'm having a big issue when using the mod with SQL Server,
> the first is the event table is not created, i had to create it manually,
> the table server is not created, i had to create it manually,
> until that there's not a big issue but looks like all constrains a foreign
> keys are wrong,
> i cannot add a device, or group or anything, just modify the the fields
> that not required constrains
> on other tables,
> another issue is that for save a vehicle, no sql, using h2 you had to
> click on all
> tabs to be able to save it, can you verify that,
> Regards.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/vitalidze/traccar-web/issues/669

## 

Kind regards, Vitaly Litvak

**Comment by vitalidze** [comment]
> another issue is that for save a vehicle, no sql, using h2 you had to click on all 
> tabs to be able to save it, can you verify that, 

I have just checked it myself. I cannot reproduce it neither on MySQL nor on H2. I guess you are using some version built from sources from github. You should try latest available version or build it yourself from this repository from `dev` branch.

**Comment by cabreu1981** [comment]
i was using the platform using h2 tables, and everything worked perfect, then i created an empty sql table and pointed to it, and started the service, all the tables were created but the mentioned issue presented, and yes i'm using the latest version here in dev branch,
Regards.

Carlos Abreu

**Comment by cabreu1981** [comment]
let me upload the created table to dropbox

**Comment by vitalidze** [comment]
Which issue you are talking about right now? With inability to save devices until you walk through all tabs? Or the issue with MSSQL Server?

The first one was fixed and I cannot reproduce it on my side anymore. For the second one I think I will need MS SQL to test, this will not happen soon.

**Comment by cabreu1981** [comment]
```
STATUS | wrapper  | 2016/05/09 12:19:55 | Launching a JVM...
INFO   | jvm 1    | 2016/05/09 12:19:55 | WrapperManager: Initializing...
INFO   | jvm 1    | 2016/05/09 12:19:55 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2016/05/09 12:19:55 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.2 [built 08-December-2015 22:06:04 -0800; debug? true; trace: 10]
INFO   | jvm 1    | 2016/05/09 12:19:56 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.util.log - Logging initialized @583ms
INFO   | jvm 1    | 2016/05/09 12:19:56 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> 1hgevia9g15phe8dqd342g|2eda7ebb, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.microsoft.sqlserver.jdbc.SQLServerDriver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> 1hgevia9g15phe8dqd342g|2eda7ebb, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:sqlserver://GAMES;databaseName=Bridge_LBS_Prod_6;user=sa;password=carlos1981;, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
INFO   | jvm 1    | 2016/05/09 12:19:56 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - jetty-9.2.15.v20160210
INFO   | jvm 1    | 2016/05/09 12:19:57 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@60ab3ce3{/api,null,AVAILABLE}
INFO   | jvm 1    | 2016/05/09 12:20:01 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.webapp.StandardDescriptorProcessor - NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
INFO   | jvm 1    | 2016/05/09 12:20:03 | [WrapperSimpleAppMain] WARN org.eclipse.jetty.webapp.WebAppContext - Failed startup of context o.e.j.w.WebAppContext@6113a425{/,file:/C:/Windows/Temp/jetty-0.0.0.0-8082-traccar-web.war-_-any-6979311431842415454.dir/webapp/,STARTING}{C:\Program Files (x86)\Traccar\traccar-web.war}
INFO   | jvm 1    | 2016/05/09 12:20:03 | java.lang.RuntimeException: Unable to perform DB migrations
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:77)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at javax.servlet.GenericServlet.init(GenericServlet.java:244)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.init(RemoteServiceServlet.java:168)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.google.inject.servlet.ServletDefinition.init(ServletDefinition.java:117)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.google.inject.servlet.ManagedServletPipeline.init(ManagedServletPipeline.java:82)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.google.inject.servlet.ManagedFilterPipeline.initPipeline(ManagedFilterPipeline.java:102)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.google.inject.servlet.GuiceFilter.init(GuiceFilter.java:172)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.servlet.FilterHolder.initialize(FilterHolder.java:138)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:852)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:298)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.server.Server.start(Server.java:387)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.server.Server.doStart(Server.java:354)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.web.WebServer.start(WebServer.java:165)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.Main.main(Main.java:35)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/05/09 12:20:03 | Caused by: javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.web.server.model.DBMigrations$SetDefaultExpiredFlagForEvents.migrate(DBMigrations.java:397)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.web.server.model.DBMigrations.migrate(DBMigrations.java:69)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.traccar.web.server.model.DataServiceImpl.init(DataServiceImpl.java:75)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   ... 32 more
INFO   | jvm 1    | 2016/05/09 12:20:03 | Caused by: org.hibernate.exception.SQLGrammarException: could not execute statement
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:123)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:211)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   ... 35 more
INFO   | jvm 1    | 2016/05/09 12:20:03 | Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'events'.
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1522)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1716)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:314)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:384)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/05/09 12:20:03 |   ... 43 more
INFO   | jvm 1    | 2016/05/09 12:20:03 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.ServerConnector - Started ServerConnector@7005eab2{HTTP/1.1}{0.0.0.0:8082}
INFO   | jvm 1    | 2016/05/09 12:20:03 | [WrapperSimpleAppMain] INFO org.eclipse.jetty.server.Server - Started @8339ms
```

**Comment by vitalidze** [comment]
Well, it looks like the `events` is a reserved word in MSSQL and thus table with such name cannot be created (or it needs to be escaped somehow). So, this means that the web UI Mod is not compatible with this database engine at least without modifications to the code. I recommend to use MySQL instead.

**Comment by cabreu1981** [comment]
i tested it now and seems everything is working fine, 
and yes events is a reserved word in sql server since 2008 version.
big thanks, 
i managed  how to send commands to gt06 devices,
those are very popular in those days.
if you need some help you can reach me out.
Regards,

Carlos Abreu.

**Comment by vitalidze** [comment]
> if you need some help you can reach me out.

Well, there are many outdated articles on the web site: http://traccar.litvak.su/features/ (like [this one](http://traccar.litvak.su/features/change-device-icon.html)). If you want to help updating them (at least screen shots) then please contact me by email (from my github profile).

**Comment by vitalidze** [comment]
BTW looks like it is possible to force hibernate to escape table names: http://stackoverflow.com/questions/2224503/creating-field-with-reserved-word-name-with-jpa I will try to check this out in one of the next releases.

**Comment by vitalidze** [comment]
Finally, I got the solution for the SQL Server. The main incompatibility issue here is that by default in MS SQL Server database there is already a view named `events`, located under `sys` schema. Thus, during schema update the necessary table is not get created because system finds it under `sys` schema, actually it does not care about any schema at the moment, just walks through all tables from the database. So, the solution is to force application to use correct schema in the database, this schema for user's tables is named `dbo`. To do it here are steps:

1) Unpack `WEB-INF/classes/META-INF/persistence.xml` file from `traccar-web.war` zip-archive.

2) Update `release` configuration:

``` xml
  <persistence-unit name="release">
    <non-jta-data-source>java:/DefaultDS</non-jta-data-source>
    <properties>
      <property name="hibernate.show_sql" value="false"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
    </properties>
  </persistence-unit>
```

(this version is taken from latest version at the moment, it may differ in future releases)

Add there a property named default schema into the `properties` block:

``` xml
  <persistence-unit name="release">
    <non-jta-data-source>java:/DefaultDS</non-jta-data-source>
    <properties>
      <property name="hibernate.show_sql" value="false"/>
      <property name="hibernate.hbm2ddl.auto" value="update"/>
      <!-- set up default schema -->
      <property name="hibernate.default_schema" value="dbo" />
    </properties>
  </persistence-unit>
```

Save changes to the `persistence.xml` file.

3) Pack updated `persistence.xml` file back to the `traccar-web.war` file. For example this can be done with `jar` command coming with the JDK.

---

After these manipulations traccar-web system creates necessary tables and everything works just fine.
