### ISSUE TITLE
Not able to set device timezone

### ISSUE THREAD

**Issue by jayanti-prajapati** [vitalidze/traccar-web#684]
Hello,
I am using TR06 (GT06 protocol) device. Its sending the diffrent timezone time, It seems like UTC+1,  I tried to set timezone using the command but its firing exception as below.

{"reason":"java.lang.reflect.InvocationTargetException: null","success":false}

Server Log:

```
INFO   | jvm 1    | 2016/05/18 06:23:18 | [qtp2107592233-45] WARN / - Key[type=org.traccar.web.server.model.DataServiceImpl, annotation=[none]]: Unable to invoke command through reflection
INFO   | jvm 1    | 2016/05/18 06:23:18 | java.lang.reflect.InvocationTargetException
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.DataServiceImpl.sendCommand(DataServiceImpl.java:1040)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$dc66735c.CGLIB$sendCommand$2(<generated>)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$dc66735c$$FastClassByGuice$$a49ef7d2.invoke(<generated>)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:41)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.web.server.model.DataServiceImpl$$EnhancerByGuice$$dc66735c.sendCommand(<generated>)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/05/18 06:23:18 | Caused by: java.lang.RuntimeException: Command setTimezone is not supported in protocol gt06
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.BaseProtocol.sendCommand(BaseProtocol.java:45)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   at org.traccar.database.ActiveDevice.sendCommand(ActiveDevice.java:46)
INFO   | jvm 1    | 2016/05/18 06:23:18 |   ... 64 more
```

Tracker log:

2016-05-18 06:20:34  INFO: [7EF937B6] id: 5, time: 2016-05-18 12:29:40, lat: 23.04188, lon: 72.50314, speed: 0.0, course: 221.0
2016-05-18 06:25:35 DEBUG: [7EF937B6: 5023 < 27.58.35.240] HEX: 78780a13040604000200170f650d0a
2016-05-18 06:25:35 DEBUG: [7EF937B6: 5023 > 27.58.35.240] HEX: 7878051300179c460d0a
2016-05-18 06:25:35  INFO: [7EF937B6] id: 5, time: 2016-05-18 12:29:40, lat: 23.04188, lon: 72.50314, speed: 0.0, course: 221.0

 Device sending the time 2016-05-18 12:29:40 a per log. Can you please help me out to fix the timezone to IST for device.

Also, one more which column you are using for time in reports? time or serverTime?

Thanks,

**Comment by vitalidze** [comment]
The error is here:

```
INFO   | jvm 1    | 2016/05/18 06:23:18 | Caused by: java.lang.RuntimeException: Command setTimezone is not supported in protocol gt06
```

The `setTimezone` command is not supported in current protocol implementation. I have checked quickly and it's not yet supported in the latest version of traccar backend at the moment. You need to set up timezone in a different way, for example by SMS.

BTW, in latest version you should see more descriptive message instead of this:

```
{"reason":"java.lang.reflect.InvocationTargetException: null","success":false}
```

In "reason" field you should see that the command is not supported by your device/protocol.

> Also, one more which column you are using for time in reports? time or serverTime?

Everywhere in the UI the `time` column is used. The only place where `serverTime` is used in current implementation is the offline detector - the process, which figures out whether device is offline/online at the moment.

**Comment by jayanti-prajapati** [comment]
Thanks Vitalidze,
