### ISSUE TITLE
delete despositivo

### ISSUE THREAD

**Issue by MarceloMJM** [vitalidze/traccar-web#77]
hello I'm not getting exclude device appears the error message RPC

**Comment by vitalidze** [comment]
Do you mean you are trying to delete device? Please post here contents of latest `wrapper.log` file located under `logs` folder.

**Comment by MarceloMJM** [comment]
Ok.

```
INFO   | jvm 1    | 2015/01/30 20:24:05 | Caused by: 
INFO   | jvm 1    | 2015/01/30 20:24:05 | com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`traccar`.`events`, CONSTRAINT `events_fkey_position_id` FOREIGN KEY (`position_id`) REFERENCES `positions` (`id`))
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at java.lang.reflect.Constructor.newInstance(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.Util.getInstance(Util.java:383)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1049)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2334)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2262)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2246)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.doExecute(BasicExecutor.java:109)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.hql.internal.ast.exec.BasicExecutor.execute(BasicExecutor.java:78)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.hql.internal.ast.exec.DeleteExecutor.execute(DeleteExecutor.java:125)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.hql.internal.ast.QueryTranslatorImpl.executeUpdate(QueryTranslatorImpl.java:445)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.engine.query.spi.HQLQueryPlan.performExecuteUpdate(HQLQueryPlan.java:379)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.internal.SessionImpl.executeUpdate(SessionImpl.java:1286)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.internal.QueryImpl.executeUpdate(QueryImpl.java:118)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.jpa.internal.QueryImpl.internalExecuteUpdate(QueryImpl.java:371)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:78)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.traccar.web.server.model.DataServiceImpl.removeDevice(DataServiceImpl.java:367)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:39)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.traccar.web.server.model.UserCheck.invoke(UserCheck.java:39)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:688)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at javax.servlet.http.HttpServlet.service(HttpServlet.java:770)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1476)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.Server.handle(Server.java:370)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
INFO   | jvm 1    | 2015/01/30 20:24:05 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:47 | Jan 30, 2015 8:24:47 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:24:47 | INFO: Sending notification to 'ssrastreamento@mail.com'...
INFO   | jvm 1    | 2015/01/30 20:24:49 | Jan 30, 2015 8:24:49 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:24:49 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2015/01/30 20:24:49 | com.sun.mail.smtp.SMTPSendFailedException: 530-5.5.1 Authentication Required. Learn more at
INFO   | jvm 1    | 2015/01/30 20:24:49 | 530 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 l7sm11349066qaz.15 - gsmtp
INFO   | jvm 1    | 2015/01/30 20:24:49 | 
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2202)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1693)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1194)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:130)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4$$FastClassByGuice$$6d412124.invoke(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.doWork(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:49 | 
INFO   | jvm 1    | 2015/01/30 20:24:49 | Jan 30, 2015 8:24:49 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:24:49 | INFO: Sending notification to 'ssrastreamento@gmail.com'...
INFO   | jvm 1    | 2015/01/30 20:24:50 | Jan 30, 2015 8:24:50 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:24:50 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2015/01/30 20:24:50 | com.sun.mail.smtp.SMTPSendFailedException: 530-5.5.1 Authentication Required. Learn more at
INFO   | jvm 1    | 2015/01/30 20:24:50 | 530 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 11sm11302454qgt.41 - gsmtp
INFO   | jvm 1    | 2015/01/30 20:24:50 | 
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2202)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1693)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1194)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:130)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4$$FastClassByGuice$$6d412124.invoke(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.doWork(<generated>)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:24:50 | 
INFO   | jvm 1    | 2015/01/30 20:25:48 | Jan 30, 2015 8:25:47 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:25:48 | INFO: Sending notification to 'ssrastreamento@mail.com'...
INFO   | jvm 1    | 2015/01/30 20:25:49 | Jan 30, 2015 8:25:49 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:25:49 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2015/01/30 20:25:49 | com.sun.mail.smtp.SMTPSendFailedException: 530-5.5.1 Authentication Required. Learn more at
INFO   | jvm 1    | 2015/01/30 20:25:49 | 530 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 l2sm10580091qgl.30 - gsmtp
INFO   | jvm 1    | 2015/01/30 20:25:49 | 
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2202)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1693)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1194)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:130)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4$$FastClassByGuice$$6d412124.invoke(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.doWork(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:49 | 
INFO   | jvm 1    | 2015/01/30 20:25:49 | Jan 30, 2015 8:25:49 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:25:49 | INFO: Sending notification to 'ssrastreamento@gmail.com'...
INFO   | jvm 1    | 2015/01/30 20:25:51 | Jan 30, 2015 8:25:51 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender doWork
INFO   | jvm 1    | 2015/01/30 20:25:51 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2015/01/30 20:25:51 | com.sun.mail.smtp.SMTPSendFailedException: 530-5.5.1 Authentication Required. Learn more at
INFO   | jvm 1    | 2015/01/30 20:25:51 | 530 5.5.1 http://support.google.com/mail/bin/answer.py?answer=14257 c9sm11332029qas.37 - gsmtp
INFO   | jvm 1    | 2015/01/30 20:25:51 | 
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2202)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1693)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1194)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:130)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4$$FastClassByGuice$$6d412124.invoke(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$c00d86e4.doWork(<generated>)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2015/01/30 20:25:51 | 

```

**Comment by vitalidze** [comment]
It's a bug. Will try to do my best to fix it this weekend. You can delete this device after you drop all events related to it from `events` table.

**Comment by vitalidze** [comment]
Fixed, written [news](http://traccar.litvak.su/2015/01/31/zoom-to-track-feature-and-devices-removal-bugfix.html), included in [latest public available version](http://myultrashare.appspot.com/s/traccar-web/dev/latest/traccar-web.war) and [demo version](http://d.traccar.litvak.su).

**Comment by MarceloMJM** [comment]
Everything ok excellent thank you.
