### ISSUE TITLE
Giant log files

### ISSUE THREAD

**Issue by tectonny** [vitalidze/traccar-web#826]
I have 3 installed system, and now I realize that all three catch for lack of space on the server.

The one-day log folder to another reaches 20GB or more.

file type like this:
wrapper.log.20160829 = 19GB

Is to limit this log?
Or create a self-cleaning?
Or disable the logs?

**Comment by vitalidze** [comment]
You can read about logging configuration here: https://wrapper.tanukisoftware.com/doc/english/props-logging.html

However, I think you need to figure out why your files are getting so big. Read messages there, maybe you have some issues with your server configuration.

**Comment by tectonny** [comment]
I am accompanied.
But 3 different systems, can not be server, correct?

**Comment by vitalidze** [comment]
Again, there can be some issue with your server configuration.

**Comment by tectonny** [comment]
You can disable?

**Comment by vitalidze** [comment]
You can update wrapper.conf with some settings from the link I have sent you. You can even disable logging with those settings.

**Comment by andyguz** [comment]
hi  hello, I have also had this problem come to find that this record is repeated with a pattern of increase -7 until the service is restarted or if the problem only happens but in this period that comes to pass is generated in the log this message:

| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds: -7
| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds: -14

**Comment by tectonny** [comment]
I configured to limit logging to 50Mb

**Comment by andyguz** [comment]
tectonny Might help me, my email is akumakuro@gmail.com

**Comment by tectonny** [comment]
Given the statement of Vitali, I decided to test other servers.

But they all generate giant files without apparent cause.
I'm testing the following VPS:

digital Ocean
Vultr
LituaniaVps

All with 2Gb memory.

And yet it generates files between 15GB to 40GB

How can you still be a server problem?

**Comment by andyguz** [comment]
Hi, I actually tried to limit to 80 MB and only generate 4 files but still generates large files:

wrapper.logfile.maxsize = 80m
wrapper.logfile.maxfiles = 4

the VPS is running Windows Server and 2gb of ram, I've had files 6gb, something I have also noticed is that stops generating input events and output geofencing, movement off good all types of events until it returns to run the application again, talking to a friend tells me it's probably a bug traccar web UI

tectonny As clients have on the server running at the same time?

**Comment by vitalidze** [comment]
> Given the statement of Vitali, I decided to test other servers.

You got it wrong. I meant the issue is not with your VPS hosting, but with the application configuration. You need to analyize logs. My suggestion is to find out which messages are flooding your log and then update your configuration somehow to reduce the output. To figure out how to change server settings you need to find the nature of messages flooding your log files.

**Comment by andyguz08** [comment]
the message shown in the record when stops generating all events and create huge logs is:

| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds : -7
| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds : -14
| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds : -21
| 2016/09/01 10:03:30 | Imma skip it 2
| 2016/09/01 10:03:30 | Time in seconds : -28
this message is continually repeated with the difference that it subtracts 7 and is creating a record Inmes it is like a freeze Prosesa and generates a continuous loop

**Comment by marivan4** [comment]
bom dia a todos , estava me passando por isso tambem , e notava que o mysql parava tambem por falta de memoria , entao desativei a porta  dos  rastreadores que nao uso e isso melhorou e muito , tambem desativeis os log no arquivo conf.xml de all para none e true para false

**Comment by vitalidze** [comment]
@andyguz08 @andyguz I have no idea what does these messages mean. Never seen them before. I cannot find any info in google. Thus, I think you need to find some messages before the first occurrence of the "Imma skip it ... "/"Time in seconds ... " messages. This should help to find out why these messages appear. I suspect that your systems runs out of resources (like memory, or number of opened files), but I am not sure.

**Comment by tectonny** [comment]
Hello, I also think it was lack of resources, but most of the time that happens the problem is at daybreak, when no trace of activity.

**Comment by vitalidze** [comment]
So @tectonny do you have same content flooded you log files as @andyguz ? Have you seen some records in log file before it started growing?

**Comment by tectonny** [comment]
@vitalidze 
The files are more than 10Gb, it is difficult to read your content.

**Comment by andyguz** [comment]
tectonny, would be to compress the log you have and send it to your email or to upload it to a ftp then work with from the pc, being logs (text) greatly reduces its weight when compressed, what you might do is split the log into smaller archvos can do both windows and linux, with windows you can try

http://www.gdgsoft.com/gsplit/

If you like I can help to check the log.

**Comment by vitalidze** [comment]
@tectonny you can read them with any streaming reader, like `less`. See this thread for example: http://serverfault.com/questions/411280/how-to-get-less-to-seek-faster-with-large-log-files Or try solution from @andyguz to split up your files.

**Comment by tectonny** [comment]
@vitalidze I managed to catch the end to see if it helps

`INFO   | jvm 1    | 2016/09/10 02:47:51 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2016/09/10 02:47:51 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/10 02:47:51 | 
STATUS | wrapper  | 2016/09/10 02:47:51 | TERM trapped.  Shutting down.
INFO   | jvm 1    | 2016/09/10 02:47:52 | Sep 10, 2016 2:47:52 AM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/09/10 02:47:52 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/09/10 02:47:52 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO   | jvm 1    | 2016/09/10 02:47:52 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/09/10 02:47:52 | 
INFO   | jvm 1    | 2016/09/10 02:47:52 | [Thread-11] INFO org.eclipse.jetty.server.ServerConnector - Stopped ServerConnector@32900665{HTTP
/1.1}{0.0.0.0:80}
INFO   | jvm 1    | 2016/09/10 02:47:52 | [Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.w.WebAppContext@
7753f263{/,file:/tmp/jetty-0.0.0.0-80-traccar-web.war-_-any-8054076512755556136.dir/webapp/,UNAVAILABLE}{/opt/traccar/traccar-web.war}
INFO   | jvm 1    | 2016/09/10 02:47:52 | [Thread-11] INFO org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContext
Handler@662e553d{/api,null,UNAVAILABLE}
STATUS | wrapper  | 2016/09/10 02:48:04 | <-- Wrapper Stopped
(END)`

**Comment by vitalidze** [comment]
@tectonny Yes, that's definitely helps. So actually your system reaches limit on the number of open files. The socket connection is also counted, so probably your traccar server does have too many open connections. Some of these connections may be stale. Some devices don't close connections properly even after they reconnect. Thus, to fix it you can set up a `resetDelay` for the protocols you are using, which will close the connection when there are no messages for the specified number of seconds (say for five minutes, or 300 seconds). You can read about it here: https://github.com/tananaev/traccar/issues/1524

Also you can increase operating system limit on the number of open files. Just google for the `Too many open files` error and you will find many answers.

**Comment by tectonny** [comment]
Okay, I'm just using the gps103, I added the following code in traccar.xml
I will see what will happen.

`<entry key='gps103.resetDelay'>300</entry>`

**Comment by tectonny** [comment]
Hello, yet everything to normal and without error after adding the code below and restart the traccar.

Thanks for the help of all.

`<entry key='gps103.resetDelay'>300</entry>`

**Comment by andyguz** [comment]
hello tectonny, where in adicionaste the code, 
<entry key='gps103.resetDelay'>300</entry>
could you please explain.

**Comment by tectonny** [comment]
From what I understand, some doors are open for longer than necessary, this code is idle ports to more than 5 minutes (300) is closed.

Add in traccar.xml

**Comment by andyguz** [comment]
it should be this way, it is correct.

``` xml
<entry key='gps103.port'>5001</entry>
<entry key='gps103.resetDelay'>300</entry>
```

**Comment by tectonny** [comment]
No need to add the code below to each protocol you are using, mine here is gps103, looked like this:

This is a new line, is not to modify any line.
`<entry key='gps103.resetDelay'>300</entry>`

If another protocol, have to add a new line to the other. Example for mobile applications
`<entry key='osmand.resetDelay'>300</entry>`

Example to gt06:
`<entry key='gt06.resetDelay'>300</entry>`

I understand that, but wait for @vitalidze

**Comment by vitalidze** [comment]
I agree with @tectonny . However, @andyguz may have different issue. Anyway, it's worth to try setting up the `resetDelay`. Then if the problem persists - walk through the log file contents.

**Comment by tectonny** [comment]
Read your log @andyguz 
Use this command to read the end of the log:
`less -n +99p /opt/traccar/logs/wrapper.log.xxxxxx`

**Comment by andyguz** [comment]
Very good tectonny, the server works with windows,

**Comment by tectonny** [comment]
I use Linux, search command similar to Windows.

**Comment by akmal1999** [comment]
Hi, 

To keep the questions open, is there a way to wildecard all of the gpse including the app softwares for a "reset.delay" ?

thanks

**Comment by akmal1999** [comment]
like   <entry key='*.resetDelay'>300</entry>

**Comment by akmal1999** [comment]
like  ''<entry key='gt06.resetDelay'>300</entry>"

**Comment by akmal1999** [comment]
entry key='*.resetDelay'>300</entry

**Comment by vitalidze** [comment]
@akmal1999 AFAIK it is not possible. You can ask same question on [backend issue tracker](https://github.com/tananaev/traccar/issues) to find it out for sure.
