### ISSUE TITLE
Installing Web UI v3.5 on Traccar v3.6

### ISSUE THREAD

**Issue by akamomer** [vitalidze/traccar-web#843]
Can I install Web UI v3.5 on Traccar Server v3.6?

Thanks

**Comment by akamomer** [comment]
I installed Version 3.6 on my traccar 3.6, and I got the following issues:
1- no data seen for the devices.
2- Remote procedure call error.

## Server Log:

2016-09-12 02:22:14  INFO: [57685E59] connected
2016-09-12 02:22:14 DEBUG: [57685E59: 5055 < 130.193.194.161] HEX: 474554202f3f69643d3136323436352674696d657374616d703d31343732383037393138266c61743d33362e343330373135393530313635373035266c6f6e3d34342e33363833313833303536373731352673706565643d302e302662656172696e673d302e3026616c7469747564653d3834332e30303731323336333233333326626174743d37352e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4739333546204275696c642f4d4d4232394b290d0a486f73743a203130342e3133312e3138302e3130383a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2016-09-12 02:22:14 DEBUG: [57685E59: 5055 > 130.193.194.161] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-09-12 02:22:14  INFO: [57685E59] disconnected
2016-09-12 02:22:14  WARN: Field 'deviceid' doesn't have a default value - SQLException (... < QueryBuilder:435 < DataManager:507 < DefaultDataHandler:27 < ...)
2016-09-12 02:22:14  INFO: [57685E59] id: 162465, time: 2016-09-02 12:18:38, lat: 36.43072, lon: 44.36832, speed: 0.0, course: 0.0
2016-09-12 02:22:14  INFO: [6B9832C9] connected
2016-09-12 02:22:14 DEBUG: [6B9832C9: 5055 < 130.193.194.161] HEX: 474554202f3f69643d3136323436352674696d657374616d703d31343732383037393332266c61743d33362e3433323533323738323338313831266c6f6e3d34342e33373231323735383630323339342673706565643d36342e37363332393034343337383636322662656172696e673d35302e393235333838333336313831363426616c7469747564653d3834352e3730313934373538393731313226626174743d37352e3020485454502f312e310d0a557365722d4167656e743a2044616c76696b2f322e312e3020284c696e75783b20553b20416e64726f696420362e302e313b20534d2d4739333546204275696c642f4d4d4232394b290d0a486f73743a203130342e3133312e3138302e3130383a353035350d0a436f6e6e656374696f6e3a204b6565702d416c6976650d0a4163636570742d456e636f64696e673a20677a69700d0a0d0a
2016-09-12 02:22:14 DEBUG: [6B9832C9: 5055 > 130.193.194.161] HEX: 485454502f312e3120323030204f4b0d0a0d0a
2016-09-12 02:22:14  INFO: [6B9832C9] disconnected
2016-09-12 02:22:14  WARN: Field 'deviceid' doesn't have a default value - SQLException (... < QueryBuilder:435 < DataManager:507 < DefaultDataHandler:27 < ...)

## 2016-09-12 02:22:14  INFO: [6B9832C9] id: 162465, time: 2016-09-02 12:18:52, lat: 36.43253, lon: 44.37213, speed: 64.8, course: 50.9

## Wrapper Log:

INFO   | jvm 1    | 2016/09/12 02:00:14 |   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5098)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
INFO   | jvm 1    | 2016/09/12 02:00:14 |   ... 72 more

**Comment by vitalidze** [comment]
This means you haven't followed installation instructions carefully. I think you haven't dropped the traccar database and/or haven't disabled database schema updates by backend. Please double check all steps from installation instructions for 3.6: http://traccar.litvak.su/installation.html

**Comment by akamomer** [comment]
Yes, after I dropped the database and created just an empty database, the system worked fine. thanks.
