### ISSUE TITLE
WHY  the notifications do not send emails.

### ISSUE THREAD

**Issue by fvaldesc** [vitalidze/traccar-web#915]
WHY  the notifications do not send emails.

I have the email, the port, the address is all Ok
further, test button es Ok.

which could be other problem. ?
Fernando

regards
Fernando

**Comment by vitalidze** [comment]
You need to check `wrapper.log` file for error messages. Also maybe there were no events to send yet.

**Comment by fvaldesc** [comment]
com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$e89a2264.doWork(<generated>)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:38 | 
INFO   | jvm 1    | 2016/10/20 15:51:39 | Oct 20, 2016 3:51:39 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/10/20 15:51:39 | INFO: Sending Email notification to 'fvaldesc@yahoo.com'...
INFO   | jvm 1    | 2016/10/20 15:51:39 | Oct 20, 2016 3:51:39 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/10/20 15:51:39 | SEVERE: Unable to send Email message
INFO   | jvm 1    | 2016/10/20 15:51:39 | com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. w29sm24191054qtc.27 - gsmtp
INFO   | jvm 1    | 2016/10/20 15:51:39 | 
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2202)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.sun.mail.smtp.SMTPTransport.mailFrom(SMTPTransport.java:1693)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1194)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.sendEmail(NotificationServiceImpl.java:261)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender.doWork(NotificationServiceImpl.java:174)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$e89a2264.CGLIB$doWork$0(<generated>)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$e89a2264$$FastClassByGuice$$f363dd0f.invoke(<generated>)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.NotificationServiceImpl$NotificationSender$$EnhancerByGuice$$e89a2264.doWork(<generated>)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at org.traccar.web.server.model.ScheduledTask.run(ScheduledTask.java:35)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 |   at java.lang.Thread.run(Unknown Source)
INFO   | jvm 1    | 2016/10/20 15:51:39 | 
INFO   | jvm 1    | 2016/10/20 15:51:39 | Oct 20, 2016 3:51:39 PM org.traccar.web.server.model.NotificationServiceImpl$NotificationSender sendEmail
INFO   | jvm 1    | 2016/10/20 15:51:39 | INFO: Sending Email notification to 'fvaldesc@yahoo.com'..

**Comment by vitalidze** [comment]
> INFO | jvm 1 | 2016/10/20 15:51:39 | com.sun.mail.smtp.SMTPSendFailedException: 530 5.7.0 Must issue a STARTTLS command first. w29sm24191054qtc.27 - gsmtp

This means you have configured SMTP server incorrectly. I guess you should use `STARTTLS` encryption.
