### ISSUE TITLE
Edit button for devices

### ISSUE THREAD

**Issue by xizoaziz** [vitalidze/traccar-web#924]
Hi all 
sometimes Edit button has no action، though I select a device ، it may work with some devices and some not . if logged out  the system and try again it works fine for a while and got not work again for some random devices .
- the log for the server is clean and no issues reported .
  
  Did anyone encounter this issue before ?

**Comment by vitalidze** [comment]
You need to check web browser console for error messages when the problem will reproduce next time.

**Comment by xizoaziz** [comment]
hello @vitalidze here is the console : 

![screen shot 2016-10-27 at 11 55 05 pm](https://cloud.githubusercontent.com/assets/12040752/19785217/4c33a316-9ca1-11e6-914a-91ce5ff688b0.png)

<img width="1280" alt="screen shot 2016-10-28 at 12 01 33 am" src="https://cloud.githubusercontent.com/assets/12040752/19785381/d6025196-9ca1-11e6-8b6e-20e9650aece8.png">

**Comment by vitalidze** [comment]
Well, it looks like it needs some debugging because stack trace is hidden from here. You can connect to your server with application running in SuperDevMode in IDE. Then you can debug this issue.

**Comment by xizoaziz** [comment]
I did as advise, but nothing in the console for the IDE .
in Chrome I found this error : 

<img width="833" alt="screen shot 2016-10-28 at 10 18 12 pm" src="https://cloud.githubusercontent.com/assets/12040752/19819252/79206e48-9d5c-11e6-94b1-54a9e17976d2.png">

**Comment by vitalidze** [comment]
This is thrown from GWT source, but we need to find a place in `traccar-web` code, from which it is thrown.

**Comment by xizoaziz** [comment]
@vitalidze  I debugged it as super Dev mode but nothing in IDE console , the only error raised in browser : 

Uncaught UmbrellaException_5_g$**gwt$backingJsError: Error: Exception caught: (TypeError) : Cannot read property 'iterator_52_g$' of undefined
    at StackTraceCreator$CollectorModern_1_g$.collect_2_g$ [as collect_4_g$](traccar-0.js:19767:38)
    at captureStackTrace_0_g$ (traccar-0.js:19593:18)
    at UmbrellaException_5_g$.fillInStackTrace_0_g$ [as fillInStackTrace_1_g$](traccar-0.js:5620:3)
    at UmbrellaException_5_g$.Throwable_3_g$ (traccar-0.js:5575:8)
    at UmbrellaException_5_g$.Exception_3_g$ (traccar-0.js:5718:18)
    at UmbrellaException_5_g$.RuntimeException_3_g$ (traccar-0.js:5759:18)
    at UmbrellaException_5_g$.UmbrellaException_3_g$ (traccar-0.js:44451:25)
    at UmbrellaException_5_g$ (traccar-0.js:44512:26)
    at HandlerManager_1_g$.fireEvent_2_g$ [as fireEvent_24_g$](traccar-0.js:44043:13)
    at TextButtonCell_1_g$.fireEvent_10_g$ [as fireEvent_26_g$](traccar-0.js:88701:67)
    at TextButtonCell_1_g$.onClick_3_g$ [as onClick_38_g$](traccar-0.js:89178:10)
    at TextButtonCell_1_g$.onBrowserEvent_11_g$ [as onBrowserEvent_49_g$](traccar-0.js:89139:10)
    at TextButton_1_g$.onBrowserEvent_22_g$ [as onBrowserEvent_51_g$](traccar-0.js:149232:20)
    at TextButton_1_g$.onBrowserEvent_35_g$ [as onBrowserEvent_51_g$](traccar-0.js:159921:53)
    at dispatchEventImpl_0_g$ (traccar-0.js:61874:17)
    at dispatchEvent_4_g$ (traccar-0.js:61863:3)
    at HTMLDivElement.dispatchEvent_6_g$ (traccar-0.js:63715:3)
    at apply_0_g$ (traccar-0.js:18257:28)
    at entry0_0_g$ (traccar-0.js:18327:14)
    at HTMLDivElement.<anonymous> (traccar-0.js:18293:14)cause_1_g$: JavaScriptException_1_g$causes_1_g$: HashSet_1_g$detailMessage_0_g$: "Exception caught: (TypeError) : Cannot read property 'iterator_52_g$' of undefined"stackTrace_1_g$: null__proto**: Object

**Comment by vitalidze** [comment]
It looks like something is wrong with the device profile. In particular, some collection is not defined or device profile is not loaded at all. You should try debugging opening of `DeviceDialog` step-by-step to see what's wrong.
