### ISSUE TITLE
Traccar 3.6 Login Problem..

### ISSUE THREAD

**Issue by waranon** [vitalidze/traccar-web#940]
I've tried to install a fresh traccar 3.6 from http://traccar.litvak.su/installation.html
Every step has been performed but I cannot Login, It said "Username/Password Invalid"
I tried to drop user table on MySQL database and re-run service again but no luck. 

Register function is work fine.

````
INFO   | jvm 1    | 2016/11/04 09:09:30 | Nov 04, 2016 9:09:30 AM org.traccar.web.server.model.MethodCallLogger invoke
INFO   | jvm 1    | 2016/11/04 09:09:30 | INFO: Login 'admin'
INFO   | jvm 1    | 2016/11/04 09:09:30 | [qtp535986066-52] WARN / - Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2016/11/04 09:09:30 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.login(java.lang.String,java.lang.String) throws org.traccar.web.shared.model.TraccarException' threw an unexpected exception: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:415)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:605)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:333)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:303)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.persist.PersistFilter.doFilter(PersistFilter.java:89)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.Server.handle(Server.java:499)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/11/04 09:09:30 | Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:80)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:126)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:112)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:91)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.getResultSet(AbstractLoadPlanBasedLoader.java:449)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeQueryStatement(AbstractLoadPlanBasedLoader.java:202)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:137)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:102)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:100)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:693)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:92)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1897)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:558)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:260)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:554)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection.read(AbstractPersistentCollection.java:142)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:171)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection$1.doWork(AbstractPersistentCollection.java:156)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:260)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:155)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.collection.internal.PersistentSet.size(PersistentSet.java:160)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at java.util.HashSet.<init>(HashSet.java:118)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.traccar.web.shared.model.User.<init>(User.java:64)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:158)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.traccar.web.server.model.MethodCallLogger.invoke(MethodCallLogger.java:43)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:58)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.traccar.web.server.model.DataServiceImpl.login(DataServiceImpl.java:164)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.inject.persist.jpa.JpaLocalTxnInterceptor.invoke(JpaLocalTxnInterceptor.java:66)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at java.lang.reflect.Method.invoke(Method.java:498)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       ... 42 more
INFO   | jvm 1    | 2016/11/04 09:09:30 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'traccar.users_notifications' doesn't exist
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at sun.reflect.GeneratedConstructorAccessor54.newInstance(Unknown Source)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.Util.getInstance(Util.java:387)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2549)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:1962)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:82)
INFO   | jvm 1    | 2016/11/04 09:09:30 |       ... 71 more
````

**Comment by vitalidze** [comment]
Looks like you have made some mistake during installation of the `Traccar Web UI Mod` and it hasn't created necessary tables. Here is the table, which is missing:

```
INFO   | jvm 1    | 2016/11/04 09:09:30 | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'traccar.users_notifications' doesn't exist
```

**Comment by waranon** [comment]
Do you have SQL command to create it by manual? I have tried several time
to installed it.

**Comment by vitalidze** [comment]
I don't have it. You need to figure out why it does not get created because you can have other tables missing.

**Comment by waranon** [comment]
Can you recommend MySQL version? maybe it had an error during installation caused by syntax

**Comment by vitalidze** [comment]
I have tried and succeeded with 5.1, 5.6 and 5.7. I don't think it depends on version. Maybe there are some settings in MySQL instance that you have installed. I suggest you to try installing it on some VM running something very popular like Ubuntu Server.
